// Curated pool of puzzles for the Word Chain game.
//
// A chain is a run of words where every neighbouring pair makes a compound word
// or a set phrase — SUN·FLOWER, FLOWER·BED, BED·ROOM, and so on. Players see the
// two ends and race to fill everything between them, top down.
//
// Rules the bank follows, so guesses can be checked by exact match:
//
//   * Each link is a real closed compound (BACKPACK) or a standard two-word
//     phrase (PACK RAT). No inflection tricks — "LUCK → CHARM" via *lucky*
//     charm doesn't belong here, because a player who types the right word
//     would still be told they're wrong.
//   * Answers are single words with no spaces or punctuation.
//   * Six words per chain, so every puzzle is exactly four blanks and scores
//     the same as every other one.
//
// The array below is generated. To grow the bank, add links to the LINKS table
// in `scripts/generateWordChains.mjs` and re-run it:
//
//     node scripts/generateWordChains.mjs 750
//
// It keeps every chain already here, ids untouched, and appends until it hits
// the target. Editing a chain by hand is fine too — the generator reads them
// back and works around them — but never renumber one: `player_word_chains_seen`
// is keyed by `id`, so a renamed chain reads as brand new and gets dealt again
// to the people who already solved it.
//
// Why a big bank matters: players never get the same puzzle twice, so the size
// of this list is how many games a regular group gets before selection has to
// fall back to least-seen.

export interface WordChainPuzzle {
  id: string;
  /** The whole chain, first word to last. Ends are given; the rest are blanks. */
  words: string[];
}

export const WORD_CHAINS: WordChainPuzzle[] = [
  { id: "fire-pack-rat", words: ["FIRE", "FLY", "PAPER", "BACK", "PACK", "RAT"] },
  { id: "sun-service-charge", words: ["SUN", "FLOWER", "BED", "ROOM", "SERVICE", "CHARGE"] },
  { id: "rain-fast-food", words: ["RAIN", "BOW", "TIE", "BREAK", "FAST", "FOOD"] },
  { id: "horse-shop-lift", words: ["HORSE", "SHOE", "LACE", "WORK", "SHOP", "LIFT"] },
  { id: "black-side-kick", words: ["BLACK", "BOARD", "WALK", "WAY", "SIDE", "KICK"] },
  { id: "snow-mark-down", words: ["SNOW", "BALL", "PARK", "BENCH", "MARK", "DOWN"] },
  { id: "moon-up-grade", words: ["MOON", "LIGHT", "HOUSE", "HOLD", "UP", "GRADE"] },
  { id: "butter-man-hole", words: ["BUTTER", "FLY", "WHEEL", "CHAIR", "MAN", "HOLE"] },
  { id: "heart-hall-way", words: ["HEART", "BREAK", "DOWN", "TOWN", "HALL", "WAY"] },
  { id: "fire-shelf-life", words: ["FIRE", "WOOD", "WORK", "BOOK", "SHELF", "LIFE"] },
  { id: "gold-hill-side", words: ["GOLD", "FISH", "HOOK", "UP", "HILL", "SIDE"] },
  { id: "sand-game-plan", words: ["SAND", "PAPER", "CLIP", "BOARD", "GAME", "PLAN"] },
  { id: "key-hole-punch", words: ["KEY", "NOTE", "BOOK", "WORM", "HOLE", "PUNCH"] },
  { id: "water-work-force", words: ["WATER", "FALL", "BACK", "FIRE", "WORK", "FORCE"] },
  { id: "hand-up-root", words: ["HAND", "BAG", "PIPE", "LINE", "UP", "ROOT"] },
  { id: "tooth-read-out", words: ["TOOTH", "BRUSH", "FIRE", "PROOF", "READ", "OUT"] },
  { id: "dog-side-walk", words: ["DOG", "HOUSE", "WORK", "OUT", "SIDE", "WALK"] },
  { id: "rail-case-work", words: ["RAIL", "ROAD", "SIDE", "SHOW", "CASE", "WORK"] },
  { id: "silver-food-chain", words: ["SILVER", "WARE", "HOUSE", "PLANT", "FOOD", "CHAIN"] },
  { id: "eye-car-pool", words: ["EYE", "BROW", "BEAT", "BOX", "CAR", "POOL"] },
  { id: "over-power-house", words: ["OVER", "TIME", "LINE", "MAN", "POWER", "HOUSE"] },
  { id: "cup-coat-rack", words: ["CUP", "CAKE", "WALK", "OVER", "COAT", "RACK"] },
  { id: "night-water-melon", words: ["NIGHT", "FALL", "OUT", "BREAK", "WATER", "MELON"] },
  { id: "life-point-blank", words: ["LIFE", "GUARD", "RAIL", "WAY", "POINT", "BLANK"] },
  { id: "home-ground-hog", words: ["HOME", "WORK", "HORSE", "PLAY", "GROUND", "HOG"] },
  { id: "super-work-shop", words: ["SUPER", "STAR", "FISH", "NET", "WORK", "SHOP"] },
  { id: "head-up-town", words: ["HEAD", "PHONE", "BOOK", "MARK", "UP", "TOWN"] },
  { id: "back-shift-key", words: ["BACK", "BONE", "YARD", "STICK", "SHIFT", "KEY"] },
  { id: "pan-lift-off", words: ["PAN", "CAKE", "BATTER", "UP", "LIFT", "OFF"] },
  { id: "green-pass-word", words: ["GREEN", "HOUSE", "HOLD", "OVER", "PASS", "WORD"] },
  { id: "foot-room-mate", words: ["FOOT", "BALL", "GAME", "SHOW", "ROOM", "MATE"] },
  { id: "short-stick-shift", words: ["SHORT", "CUT", "BACK", "YARD", "STICK", "SHIFT"] },
  { id: "red-wheel-chair", words: ["RED", "HEAD", "BAND", "WAGON", "WHEEL", "CHAIR"] },
  { id: "tea-fire-place", words: ["TEA", "SPOON", "FEED", "BACK", "FIRE", "PLACE"] },
  { id: "air-land-scape", words: ["AIR", "BAG", "PIPE", "DREAM", "LAND", "SCAPE"] },
  { id: "fire-off-shore", words: ["FIRE", "ARM", "CHAIR", "LIFT", "OFF", "SHORE"] },
  { id: "sea-top-hat", words: ["SEA", "SHELL", "FISH", "TANK", "TOP", "HAT"] },
  { id: "hot-up-grade", words: ["HOT", "DOG", "TAG", "LINE", "UP", "GRADE"] },
  { id: "snow-life-guard", words: ["SNOW", "MAN", "POWER", "PLANT", "LIFE", "GUARD"] },
  { id: "cross-out-side", words: ["CROSS", "WALK", "OVER", "LOOK", "OUT", "SIDE"] },
  { id: "saw-out", words: ["SAW", "DUST", "PAN", "CAKE", "WALK", "OUT"] },
  { id: "book-work", words: ["BOOK", "SHELF", "LIFE", "TIME", "FRAME", "WORK"] },
  { id: "man-up", words: ["MAN", "POWER", "BOAT", "YARD", "STICK", "UP"] },
  { id: "sun-hat", words: ["SUN", "SET", "UP", "HILL", "TOP", "HAT"] },
  { id: "match-run", words: ["MATCH", "BOX", "CAR", "WASH", "OUT", "RUN"] },
  { id: "bow-frame", words: ["BOW", "TIE", "BREAK", "OUT", "DOOR", "FRAME"] },
  { id: "safe-man", words: ["SAFE", "HOUSE", "BOAT", "YARD", "WORK", "MAN"] },
  { id: "flower-night", words: ["FLOWER", "SHOP", "FLOOR", "BOARD", "GAME", "NIGHT"] },
  { id: "burn-side", words: ["BURN", "OUT", "POST", "MARK", "DOWN", "SIDE"] },
  { id: "long-tower", words: ["LONG", "HAND", "GUN", "SHOT", "CLOCK", "TOWER"] },
  { id: "bus-down", words: ["BUS", "STOP", "WATCH", "WORD", "COUNT", "DOWN"] },
  { id: "goal-bowl", words: ["GOAL", "LINE", "MAN", "HOLE", "PUNCH", "BOWL"] },
  { id: "master-board", words: ["MASTER", "KEY", "HOLE", "PUNCH", "CARD", "BOARD"] },
  { id: "truck-bone", words: ["TRUCK", "STOP", "OVER", "COAT", "TAIL", "BONE"] },
  { id: "ghost-court", words: ["GHOST", "TOWN", "HOUSE", "PLANT", "FOOD", "COURT"] },
  { id: "box-business", words: ["BOX", "SPRING", "BOARD", "GAME", "SHOW", "BUSINESS"] },
  { id: "micro-boat", words: ["MICRO", "PHONE", "BOOK", "CLUB", "HOUSE", "BOAT"] },
  { id: "bar-mate", words: ["BAR", "CODE", "WORD", "PLAY", "ROOM", "MATE"] },
  { id: "run-charge", words: ["RUN", "DOWN", "PLAY", "ROOM", "SERVICE", "CHARGE"] },
  { id: "break-cabin", words: ["BREAK", "DOWN", "PLAY", "BACK", "LOG", "CABIN"] },
  { id: "moon-back", words: ["MOON", "WALK", "OVER", "HEAD", "SET", "BACK"] },
  { id: "watch-dust", words: ["WATCH", "DOG", "FOOD", "CHAIN", "SAW", "DUST"] },
  { id: "date-up", words: ["DATE", "BOOK", "SHELF", "LIFE", "LINE", "UP"] },
  { id: "rule-road", words: ["RULE", "BOOK", "STORE", "ROOM", "SERVICE", "ROAD"] },
  { id: "bread-way", words: ["BREAD", "BOX", "SPRING", "BOARD", "WALK", "WAY"] },
  { id: "score-word", words: ["SCORE", "BOARD", "GAME", "NIGHT", "WATCH", "WORD"] },
  { id: "week-game", words: ["WEEK", "NIGHT", "LIGHT", "SWITCH", "BOARD", "GAME"] },
  { id: "path-plan", words: ["PATH", "WAY", "SIDE", "BOARD", "GAME", "PLAN"] },
  { id: "lime-way", words: ["LIME", "LIGHT", "SWITCH", "BOARD", "WALK", "WAY"] },
  { id: "drum-bench", words: ["DRUM", "BEAT", "BOX", "CAR", "PARK", "BENCH"] },
  { id: "news-card", words: ["NEWS", "PAPER", "WORK", "OUT", "POST", "CARD"] },
  { id: "look-charge", words: ["LOOK", "OUT", "BREAK", "ROOM", "SERVICE", "CHARGE"] },
  { id: "tag-punch", words: ["TAG", "TEAM", "WORK", "MAN", "HOLE", "PUNCH"] },
  { id: "club-walk", words: ["CLUB", "HOUSE", "HOLD", "OVER", "SLEEP", "WALK"] },
  { id: "stage-keeper", words: ["STAGE", "HAND", "PICK", "POCKET", "BOOK", "KEEPER"] },
  { id: "cheese-blank", words: ["CHEESE", "CAKE", "WALK", "WAY", "POINT", "BLANK"] },
  { id: "world-blank", words: ["WORLD", "WAR", "PATH", "WAY", "POINT", "BLANK"] },
  { id: "worm-beat", words: ["WORM", "HOLE", "PUNCH", "LINE", "UP", "BEAT"] },
  { id: "smoke-square", words: ["SMOKE", "HOUSE", "HOLD", "UP", "TOWN", "SQUARE"] },
  { id: "finger-work", words: ["FINGER", "PRINT", "OUT", "DOOR", "FRAME", "WORK"] },
  { id: "pack-wife", words: ["PACK", "HORSE", "FLY", "WHEEL", "HOUSE", "WIFE"] },
  { id: "lumber-place", words: ["LUMBER", "YARD", "STICK", "SHIFT", "WORK", "PLACE"] },
  { id: "body-mark", words: ["BODY", "GUARD", "DOG", "WOOD", "LAND", "MARK"] },
  { id: "class-work", words: ["CLASS", "ROOM", "SERVICE", "ROAD", "HOUSE", "WORK"] },
  { id: "plant-side", words: ["PLANT", "LIFE", "TIME", "TABLE", "TOP", "SIDE"] },
  { id: "stair-lamp", words: ["STAIR", "CASE", "WORK", "SHOP", "FLOOR", "LAMP"] },
  { id: "bean-shop", words: ["BEAN", "BAG", "LADY", "FINGER", "PRINT", "SHOP"] },
  { id: "care-out", words: ["CARE", "FREE", "WAY", "SIDE", "WALK", "OUT"] },
  { id: "corn-way", words: ["CORN", "FIELD", "DAY", "CARE", "FREE", "WAY"] },
  { id: "chair-way", words: ["CHAIR", "LIFT", "OFF", "HAND", "RAIL", "WAY"] },
  { id: "window-out", words: ["WINDOW", "SHOP", "FLOOR", "BOARD", "WALK", "OUT"] },
  { id: "paper-over", words: ["PAPER", "BACK", "SPACE", "BAR", "FLY", "OVER"] },
  { id: "pipe-walk", words: ["PIPE", "LINE", "DRIVE", "WAY", "SIDE", "WALK"] },
  { id: "lace-room", words: ["LACE", "WORK", "SHOP", "FLOOR", "BOARD", "ROOM"] },
  { id: "tie-road", words: ["TIE", "CLIP", "BOARD", "ROOM", "SERVICE", "ROAD"] },
  { id: "letter-back", words: ["LETTER", "HEAD", "COUNT", "DOWN", "FALL", "BACK"] },
  { id: "dream-down", words: ["DREAM", "TEAM", "WORK", "BOOK", "MARK", "DOWN"] },
  { id: "wind-place", words: ["WIND", "PIPE", "DREAM", "TEAM", "WORK", "PLACE"] },
  { id: "red-wright", words: ["RED", "LINE", "MAN", "POWER", "PLAY", "WRIGHT"] },
  { id: "home-mate", words: ["HOME", "WORK", "BENCH", "PRESS", "ROOM", "MATE"] },
  { id: "sign-work", words: ["SIGN", "POST", "GAME", "SHOW", "CASE", "WORK"] },
  { id: "drive-mate", words: ["DRIVE", "WAY", "SIDE", "BOARD", "ROOM", "MATE"] },
  { id: "root-night", words: ["ROOT", "STOCK", "YARD", "WORK", "WEEK", "NIGHT"] },
  { id: "tele-style", words: ["TELE", "PHONE", "BOOK", "SHELF", "LIFE", "STYLE"] },
  { id: "rose-way", words: ["ROSE", "WOOD", "LAND", "LINE", "DRIVE", "WAY"] },
  { id: "whirl-line", words: ["WHIRL", "WIND", "FALL", "BACK", "SIDE", "LINE"] },
  { id: "pine-room", words: ["PINE", "TREE", "HOUSE", "KEY", "BOARD", "ROOM"] },
  { id: "law-kind", words: ["LAW", "SUIT", "CASE", "WORK", "MAN", "KIND"] },
  { id: "log-rail", words: ["LOG", "BOOK", "SHELF", "LIFE", "GUARD", "RAIL"] },
  { id: "push-work", words: ["PUSH", "OVER", "PASS", "BOOK", "CASE", "WORK"] },
  { id: "cake-out", words: ["CAKE", "WALK", "OVER", "NIGHT", "STAND", "OUT"] },
  { id: "fly-table", words: ["FLY", "PAPER", "BACK", "UP", "TURN", "TABLE"] },
  { id: "hall-mate", words: ["HALL", "WAY", "SIDE", "SHOW", "ROOM", "MATE"] },
  { id: "pillow-pipe", words: ["PILLOW", "CASE", "WORK", "BOOK", "BAG", "PIPE"] },
  { id: "speed-time", words: ["SPEED", "BOAT", "YARD", "WORK", "DAY", "TIME"] },
  { id: "gold-mark", words: ["GOLD", "MINE", "FIELD", "WORK", "BOOK", "MARK"] },
  { id: "blue-side", words: ["BLUE", "GRASS", "LAND", "MARK", "DOWN", "SIDE"] },
  { id: "horse-line", words: ["HORSE", "PLAY", "BOOK", "STORE", "FRONT", "LINE"] },
  { id: "hot-guy", words: ["HOT", "DOG", "WOOD", "LAND", "FALL", "GUY"] },
  { id: "iron-fill", words: ["IRON", "WORK", "DAY", "DREAM", "LAND", "FILL"] },
  { id: "soap-mate", words: ["SOAP", "BOX", "SPRING", "BREAK", "ROOM", "MATE"] },
  { id: "high-side", words: ["HIGH", "LAND", "LINE", "UP", "HILL", "SIDE"] },
  { id: "sound-suit", words: ["SOUND", "PROOF", "READ", "OUT", "LAW", "SUIT"] },
  { id: "mouse-house", words: ["MOUSE", "TRAP", "DOOR", "STOP", "LIGHT", "HOUSE"] },
  { id: "cross-rail", words: ["CROSS", "WORD", "PLAY", "BACK", "HAND", "RAIL"] },
  { id: "flag-roast", words: ["FLAG", "STONE", "WALL", "FLOWER", "POT", "ROAST"] },
  { id: "egg-grade", words: ["EGG", "SHELL", "FISH", "HOOK", "UP", "GRADE"] },
  { id: "over-point", words: ["OVER", "TIME", "LINE", "DRIVE", "WAY", "POINT"] },
  { id: "lip-office", words: ["LIP", "STICK", "UP", "BEAT", "BOX", "OFFICE"] },
  { id: "tea-off", words: ["TEA", "BAG", "LADY", "FINGER", "TIP", "OFF"] },
  { id: "mail-book", words: ["MAIL", "MAN", "POWER", "PLAY", "DATE", "BOOK"] },
  { id: "hand-stone", words: ["HAND", "GUN", "BOAT", "HOUSE", "KEY", "STONE"] },
  { id: "weather-drive", words: ["WEATHER", "MAN", "HOLE", "PUNCH", "LINE", "DRIVE"] },
  { id: "mine-scale", words: ["MINE", "FIELD", "GOAL", "LINE", "UP", "SCALE"] },
  { id: "roll-trip", words: ["ROLL", "OVER", "LOOK", "OUT", "FIELD", "TRIP"] },
  { id: "tape-set", words: ["TAPE", "DECK", "CHAIR", "LIFT", "OFF", "SET"] },
  { id: "snow-wall", words: ["SNOW", "FALL", "BACK", "BONE", "DRY", "WALL"] },
  { id: "short-goal", words: ["SHORT", "HAND", "STAND", "OUT", "FIELD", "GOAL"] },
  { id: "pan-dog", words: ["PAN", "CAKE", "WALK", "OVER", "LAP", "DOG"] },
  { id: "cover-front", words: ["COVER", "UP", "DATE", "BOOK", "STORE", "FRONT"] },
  { id: "touch-out", words: ["TOUCH", "STONE", "WALL", "PAPER", "CUT", "OUT"] },
  { id: "print-boat", words: ["PRINT", "OUT", "LINE", "MAN", "POWER", "BOAT"] },
  { id: "test-park", words: ["TEST", "RUN", "DOWN", "SIDE", "CAR", "PARK"] },
  { id: "lift-chair", words: ["LIFT", "OFF", "ROAD", "SIDE", "ARM", "CHAIR"] },
  { id: "farm-mark", words: ["FARM", "LAND", "SLIDE", "RULE", "BOOK", "MARK"] },
  { id: "snake-guy", words: ["SNAKE", "SKIN", "CARE", "FREE", "FALL", "GUY"] },
  { id: "pick-right", words: ["PICK", "POCKET", "BOOK", "MARK", "DOWN", "RIGHT"] },
  { id: "flood-night", words: ["FLOOD", "LIGHT", "YEAR", "END", "GAME", "NIGHT"] },
  { id: "tear-drive", words: ["TEAR", "DROP", "DOWN", "TIME", "LINE", "DRIVE"] },
  { id: "lady-alike", words: ["LADY", "FINGER", "PRINT", "OUT", "LOOK", "ALIKE"] },
  { id: "low-house", words: ["LOW", "LAND", "SLIDE", "SHOW", "BOAT", "HOUSE"] },
  { id: "coat-book", words: ["COAT", "TAIL", "BONE", "HEAD", "PHONE", "BOOK"] },
  { id: "camp-study", words: ["CAMP", "GROUND", "RULE", "BOOK", "CASE", "STUDY"] },
  { id: "tide-name", words: ["TIDE", "POOL", "SIDE", "BAR", "CODE", "NAME"] },
  { id: "waist-box", words: ["WAIST", "BAND", "STAND", "UP", "BEAT", "BOX"] },
  { id: "air-hunt", words: ["AIR", "BAG", "PIPE", "LINE", "MAN", "HUNT"] },
  { id: "clip-alike", words: ["CLIP", "BOARD", "WALK", "OVER", "LOOK", "ALIKE"] },
  { id: "brush-cloud", words: ["BRUSH", "FIRE", "WOOD", "WIND", "STORM", "CLOUD"] },
  { id: "glass-floor", words: ["GLASS", "WARE", "HOUSE", "WORK", "SHOP", "FLOOR"] },
  { id: "full-out", words: ["FULL", "BACK", "BONE", "YARD", "WORK", "OUT"] },
  { id: "hide-study", words: ["HIDE", "OUT", "LAW", "SUIT", "CASE", "STUDY"] },
  { id: "hair-load", words: ["HAIR", "PIN", "WHEEL", "HOUSE", "BOAT", "LOAD"] },
  { id: "feather-notch", words: ["FEATHER", "BED", "POST", "BOX", "TOP", "NOTCH"] },
  { id: "part-way", words: ["PART", "TIME", "CARD", "BOARD", "WALK", "WAY"] },
  { id: "ever-lift", words: ["EVER", "GREEN", "THUMB", "PRINT", "SHOP", "LIFT"] },
  { id: "butter-door", words: ["BUTTER", "FLY", "OVER", "LOOK", "OUT", "DOOR"] },
  { id: "skin-blank", words: ["SKIN", "CARE", "FREE", "WAY", "POINT", "BLANK"] },
  { id: "fire-spring", words: ["FIRE", "FLY", "OVER", "TAKE", "OFF", "SPRING"] },
  { id: "cut-meet", words: ["CUT", "OUT", "BREAK", "FAST", "TRACK", "MEET"] },
  { id: "desk-work", words: ["DESK", "TOP", "GUN", "SHOT", "CLOCK", "WORK"] },
  { id: "pool-suit", words: ["POOL", "SIDE", "WALK", "OUT", "LAW", "SUIT"] },
  { id: "field-load", words: ["FIELD", "GOAL", "POST", "MARK", "UP", "LOAD"] },
  { id: "food-hold", words: ["FOOD", "TRUCK", "STOP", "LIGHT", "HOUSE", "HOLD"] },
  { id: "bench-pal", words: ["BENCH", "MARK", "DOWN", "PLAY", "PEN", "PAL"] },
  { id: "paint-area", words: ["PAINT", "BRUSH", "FIRE", "ARM", "REST", "AREA"] },
  { id: "tooth-burst", words: ["TOOTH", "BRUSH", "FIRE", "STORM", "CLOUD", "BURST"] },
  { id: "ear-top", words: ["EAR", "DRUM", "ROLL", "OVER", "LAP", "TOP"] },
  { id: "brain-back", words: ["BRAIN", "CHILD", "CARE", "FREE", "FALL", "BACK"] },
  { id: "down-feed", words: ["DOWN", "PLAY", "TIME", "TABLE", "SPOON", "FEED"] },
  { id: "lock-away", words: ["LOCK", "DOWN", "FALL", "OUT", "CAST", "AWAY"] },
  { id: "sword-off", words: ["SWORD", "FISH", "EYE", "DROP", "KICK", "OFF"] },
  { id: "mind-way", words: ["MIND", "SET", "BACK", "SEAT", "BELT", "WAY"] },
  { id: "read-drain", words: ["READ", "OUT", "BACK", "FIRE", "STORM", "DRAIN"] },
  { id: "team-shore", words: ["TEAM", "WORK", "SHOP", "LIFT", "OFF", "SHORE"] },
  { id: "up-coat", words: ["UP", "SIDE", "SHOW", "BOAT", "HOUSE", "COAT"] },
  { id: "wheel-shift", words: ["WHEEL", "HOUSE", "BOAT", "YARD", "STICK", "SHIFT"] },
  { id: "sling-plant", words: ["SLING", "SHOT", "GUN", "BOAT", "HOUSE", "PLANT"] },
  { id: "tip-stock", words: ["TIP", "OFF", "SET", "UP", "ROOT", "STOCK"] },
  { id: "mark-line", words: ["MARK", "UP", "SIDE", "SHOW", "TIME", "LINE"] },
  { id: "mother-alike", words: ["MOTHER", "LAND", "FALL", "OUT", "LOOK", "ALIKE"] },
  { id: "back-way", words: ["BACK", "SIDE", "WALK", "OUT", "DOOR", "WAY"] },
  { id: "pass-bell", words: ["PASS", "BOOK", "STORE", "FRONT", "DOOR", "BELL"] },
  { id: "shift-night", words: ["SHIFT", "WORK", "WEEK", "END", "GAME", "NIGHT"] },
  { id: "shot-cut", words: ["SHOT", "CLOCK", "WORK", "HORSE", "HAIR", "CUT"] },
  { id: "neck-step", words: ["NECK", "TIE", "BREAK", "DOWN", "SIDE", "STEP"] },
  { id: "gate-walk", words: ["GATE", "POST", "MARK", "UP", "SIDE", "WALK"] },
  { id: "side-trip", words: ["SIDE", "CAR", "WASH", "OUT", "FIELD", "TRIP"] },
  { id: "bone-line", words: ["BONE", "YARD", "STICK", "UP", "STREAM", "LINE"] },
  { id: "copy-load", words: ["COPY", "CAT", "FISH", "NET", "WORK", "LOAD"] },
  { id: "spring-work", words: ["SPRING", "WATER", "BOTTLE", "NECK", "LACE", "WORK"] },
  { id: "fall-end", words: ["FALL", "BACK", "GROUND", "RULE", "BOOK", "END"] },
  { id: "coffee-car", words: ["COFFEE", "TABLE", "TOP", "HAT", "BOX", "CAR"] },
  { id: "cook-man", words: ["COOK", "OUT", "FIELD", "GOAL", "LINE", "MAN"] },
  { id: "bottle-ball", words: ["BOTTLE", "NECK", "TIE", "BREAK", "FAST", "BALL"] },
  { id: "sail-fight", words: ["SAIL", "BOAT", "HOUSE", "PLANT", "FOOD", "FIGHT"] },
  { id: "meal-case", words: ["MEAL", "TIME", "FRAME", "WORK", "BOOK", "CASE"] },
  { id: "pin-tower", words: ["PIN", "BALL", "GAME", "NIGHT", "WATCH", "TOWER"] },
  { id: "word-key", words: ["WORD", "COUNT", "DOWN", "TOWN", "HOUSE", "KEY"] },
  { id: "screen-ship", words: ["SCREEN", "DOOR", "BELL", "BOY", "FRIEND", "SHIP"] },
  { id: "free-jacket", words: ["FREE", "FALL", "OUT", "LAW", "SUIT", "JACKET"] },
  { id: "fruit-work", words: ["FRUIT", "FLY", "PAPER", "BACK", "GROUND", "WORK"] },
  { id: "name-bed", words: ["NAME", "TAG", "TEAM", "WORK", "DAY", "BED"] },
  { id: "grass-stock", words: ["GRASS", "LAND", "MARK", "UP", "ROOT", "STOCK"] },
  { id: "race-line", words: ["RACE", "HORSE", "SHOE", "STORE", "FRONT", "LINE"] },
  { id: "spoon-drive", words: ["SPOON", "FEED", "BAG", "PIPE", "LINE", "DRIVE"] },
  { id: "ice-blank", words: ["ICE", "SKATE", "PARK", "WAY", "POINT", "BLANK"] },
  { id: "sleep-bell", words: ["SLEEP", "OVER", "TIME", "OUT", "DOOR", "BELL"] },
  { id: "take-break", words: ["TAKE", "OFF", "BEAT", "BOX", "SPRING", "BREAK"] },
  { id: "turn-word", words: ["TURN", "OUT", "SIDE", "BAR", "CODE", "WORD"] },
  { id: "base-room", words: ["BASE", "CAMP", "GROUND", "FLOOR", "BOARD", "ROOM"] },
  { id: "shadow-put", words: ["SHADOW", "BOX", "TOP", "GUN", "SHOT", "PUT"] },
  { id: "school-food", words: ["SCHOOL", "BOOK", "CLUB", "HOUSE", "PLANT", "FOOD"] },
  { id: "hook-mat", words: ["HOOK", "SHOT", "CLOCK", "WORK", "PLACE", "MAT"] },
  { id: "oil-mate", words: ["OIL", "FIELD", "DAY", "DREAM", "TEAM", "MATE"] },
  { id: "stand-load", words: ["STAND", "OUT", "SIDE", "SHOW", "BOAT", "LOAD"] },
  { id: "shelf-point", words: ["SHELF", "LIFE", "LONG", "HAND", "STAND", "POINT"] },
  { id: "post-boat", words: ["POST", "GAME", "NIGHT", "CLUB", "HOUSE", "BOAT"] },
  { id: "wild-house", words: ["WILD", "LIFE", "GUARD", "RAIL", "ROAD", "HOUSE"] },
  { id: "force-team", words: ["FORCE", "FEED", "BAG", "PIPE", "DREAM", "TEAM"] },
  { id: "beat-room", words: ["BEAT", "BOX", "CAR", "WASH", "BOARD", "ROOM"] },
  { id: "wood-around", words: ["WOOD", "WIND", "FALL", "OUT", "RUN", "AROUND"] },
  { id: "motor-man", words: ["MOTOR", "BOAT", "YARD", "WORK", "HORSE", "MAN"] },
  { id: "shore-room", words: ["SHORE", "BIRD", "SONG", "BOOK", "STORE", "ROOM"] },
  { id: "work-man", words: ["WORK", "FORCE", "FIELD", "GOAL", "POST", "MAN"] },
  { id: "mouth-son", words: ["MOUTH", "WASH", "OUT", "DOOR", "STEP", "SON"] },
  { id: "sheep-over", words: ["SHEEP", "DOG", "FOOD", "TRUCK", "STOP", "OVER"] },
  { id: "pocket-rack", words: ["POCKET", "BOOK", "CLUB", "HOUSE", "COAT", "RACK"] },
  { id: "guard-out", words: ["GUARD", "HOUSE", "FLY", "OVER", "TAKE", "OUT"] },
  { id: "soft-cap", words: ["SOFT", "WOOD", "WORK", "WEEK", "NIGHT", "CAP"] },
  { id: "shell-station", words: ["SHELL", "FISH", "NET", "WORK", "SPACE", "STATION"] },
  { id: "life-driver", words: ["LIFE", "GUARD", "DOG", "FOOD", "TRUCK", "DRIVER"] },
  { id: "straw-color", words: ["STRAW", "HAT", "BOX", "SPRING", "WATER", "COLOR"] },
  { id: "fast-release", words: ["FAST", "BALL", "PARK", "BENCH", "PRESS", "RELEASE"] },
  { id: "wash-gown", words: ["WASH", "OUT", "BREAK", "FAST", "BALL", "GOWN"] },
  { id: "fish-book", words: ["FISH", "FOOD", "COURT", "YARD", "WORK", "BOOK"] },
  { id: "walk-cap", words: ["WALK", "OUT", "BREAK", "WATER", "BOTTLE", "CAP"] },
  { id: "net-bug", words: ["NET", "WORK", "WEEK", "DAY", "BED", "BUG"] },
  { id: "mid-game", words: ["MID", "FIELD", "GOAL", "POST", "CARD", "GAME"] },
  { id: "hold-lady", words: ["HOLD", "UP", "DATE", "BOOK", "BAG", "LADY"] },
  { id: "tank-beat", words: ["TANK", "TOP", "SIDE", "KICK", "OFF", "BEAT"] },
  { id: "shoe-drop", words: ["SHOE", "BOX", "CAR", "SEAT", "BACK", "DROP"] },
  { id: "sand-ball", words: ["SAND", "BOX", "SPRING", "BREAK", "FAST", "BALL"] },
  { id: "spy-board", words: ["SPY", "GLASS", "HOUSE", "FLY", "OVER", "BOARD"] },
  { id: "batter-sale", words: ["BATTER", "UP", "ROOT", "STOCK", "YARD", "SALE"] },
  { id: "head-back", words: ["HEAD", "LIGHT", "HOUSE", "WORK", "HORSE", "BACK"] },
  { id: "tomb-check", words: ["TOMB", "STONE", "WARE", "HOUSE", "COAT", "CHECK"] },
  { id: "town-house", words: ["TOWN", "HALL", "PASS", "BOOK", "CLUB", "HOUSE"] },
  { id: "rail-band", words: ["RAIL", "ROAD", "BED", "SIDE", "ARM", "BAND"] },
  { id: "steam-link", words: ["STEAM", "BOAT", "HOUSE", "KEY", "CHAIN", "LINK"] },
  { id: "grand-record", words: ["GRAND", "STAND", "UP", "SIDE", "TRACK", "RECORD"] },
  { id: "chain-nine", words: ["CHAIN", "SAW", "DUST", "STORM", "CLOUD", "NINE"] },
  { id: "green-lift", words: ["GREEN", "BACK", "SIDE", "ARM", "CHAIR", "LIFT"] },
  { id: "foot-list", words: ["FOOT", "LIGHT", "HOUSE", "COAT", "CHECK", "LIST"] },
  { id: "sky-law", words: ["SKY", "LIGHT", "HOUSE", "HOLD", "OUT", "LAW"] },
  { id: "cart-spin", words: ["CART", "WHEEL", "HOUSE", "COAT", "TAIL", "SPIN"] },
  { id: "pop-port", words: ["POP", "UP", "TURN", "OVER", "PASS", "PORT"] },
  { id: "stone-table", words: ["STONE", "WARE", "HOUSE", "KEY", "CARD", "TABLE"] },
  { id: "show-back", words: ["SHOW", "DOWN", "HILL", "SIDE", "KICK", "BACK"] },
  { id: "star-piece", words: ["STAR", "POWER", "PLANT", "LIFE", "TIME", "PIECE"] },
  { id: "hard-step", words: ["HARD", "HAT", "BOX", "TOP", "SIDE", "STEP"] },
  { id: "drop-kick", words: ["DROP", "DOWN", "FALL", "OUT", "SIDE", "KICK"] },
  { id: "time-load", words: ["TIME", "CARD", "GAME", "SHOW", "CASE", "LOAD"] },
  { id: "check-nail", words: ["CHECK", "BOOK", "BAG", "LADY", "FINGER", "NAIL"] },
  { id: "song-side", words: ["SONG", "BOOK", "MARK", "UP", "HILL", "SIDE"] },
  { id: "grape-stream", words: ["GRAPE", "FRUIT", "CAKE", "BATTER", "UP", "STREAM"] },
  { id: "dog-end", words: ["DOG", "HOUSE", "COAT", "CHECK", "BOOK", "END"] },
  { id: "war-worm", words: ["WAR", "HEAD", "LIGHT", "YEAR", "BOOK", "WORM"] },
  { id: "night-case", words: ["NIGHT", "STAND", "UP", "DATE", "BOOK", "CASE"] },
  { id: "zip-line", words: ["ZIP", "CODE", "WORD", "PLAY", "DATE", "LINE"] },
  { id: "wall-stage", words: ["WALL", "CLOCK", "WORK", "OUT", "BACK", "STAGE"] },
  { id: "half-rack", words: ["HALF", "TIME", "TABLE", "TOP", "COAT", "RACK"] },
  { id: "note-case", words: ["NOTE", "BOOK", "END", "GAME", "SHOW", "CASE"] },
  { id: "key-feed", words: ["KEY", "NOTE", "CARD", "TABLE", "SPOON", "FEED"] },
  { id: "peace-break", words: ["PEACE", "TIME", "FRAME", "WORK", "DAY", "BREAK"] },
  { id: "stop-shelf", words: ["STOP", "OVER", "COAT", "CHECK", "BOOK", "SHELF"] },
  { id: "hill-mill", words: ["HILL", "SIDE", "BAR", "FLY", "PAPER", "MILL"] },
  { id: "thumb-belt", words: ["THUMB", "PRINT", "OUT", "BACK", "SEAT", "BELT"] },
  { id: "year-sale", words: ["YEAR", "BOOK", "STORE", "FRONT", "YARD", "SALE"] },
  { id: "lap-holder", words: ["LAP", "DOG", "HOUSE", "WORK", "PLACE", "HOLDER"] },
  { id: "salt-clip", words: ["SALT", "WATER", "BOTTLE", "NECK", "TIE", "CLIP"] },
  { id: "love-yard", words: ["LOVE", "SONG", "BIRD", "HOUSE", "BOAT", "YARD"] },
  { id: "slide-bug", words: ["SLIDE", "RULE", "BOOK", "BAG", "LADY", "BUG"] },
  { id: "service-wagon", words: ["SERVICE", "ROAD", "BLOCK", "HEAD", "BAND", "WAGON"] },
  { id: "cup-out", words: ["CUP", "CAKE", "BATTER", "UP", "TURN", "OUT"] },
  { id: "rock-record", words: ["ROCK", "BAND", "WAGON", "TRAIN", "TRACK", "RECORD"] },
  { id: "game-horse", words: ["GAME", "SHOW", "TIME", "FRAME", "WORK", "HORSE"] },
  { id: "dry-lamp", words: ["DRY", "WALL", "FLOWER", "SHOP", "FLOOR", "LAMP"] },
  { id: "cow-hunt", words: ["COW", "HIDE", "OUT", "POST", "MAN", "HUNT"] },
  { id: "roof-force", words: ["ROOF", "TOP", "GUN", "FIRE", "WORK", "FORCE"] },
  { id: "sea-dog", words: ["SEA", "FOOD", "TRUCK", "STOP", "WATCH", "DOG"] },
  { id: "proof-care", words: ["PROOF", "READ", "OUT", "FIELD", "DAY", "CARE"] },
  { id: "dead-food", words: ["DEAD", "LOCK", "OUT", "BREAK", "FAST", "FOOD"] },
  { id: "candy-team", words: ["CANDY", "BAR", "CODE", "NAME", "TAG", "TEAM"] },
  { id: "stick-board", words: ["STICK", "SHIFT", "KEY", "NOTE", "CARD", "BOARD"] },
  { id: "river-mark", words: ["RIVER", "SIDE", "CAR", "PARK", "BENCH", "MARK"] },
  { id: "ring-work", words: ["RING", "FINGER", "PRINT", "OUT", "FIELD", "WORK"] },
  { id: "swim-game", words: ["SWIM", "TEAM", "WORK", "OUT", "POST", "GAME"] },
  { id: "ware-load", words: ["WARE", "HOUSE", "PLANT", "LIFE", "BOAT", "LOAD"] },
  { id: "light-board", words: ["LIGHT", "YEAR", "BOOK", "END", "GAME", "BOARD"] },
  { id: "grave-art", words: ["GRAVE", "STONE", "WALL", "PAPER", "CLIP", "ART"] },
  { id: "candle-lift", words: ["CANDLE", "LIGHT", "YEAR", "BOOK", "SHOP", "LIFT"] },
  { id: "eye-yard", words: ["EYE", "BALL", "BOY", "FRIEND", "SHIP", "YARD"] },
  { id: "off-stone", words: ["OFF", "SHORE", "BIRD", "HOUSE", "KEY", "STONE"] },
  { id: "street-yard", words: ["STREET", "CAR", "SEAT", "BACK", "BONE", "YARD"] },
  { id: "hat-wind", words: ["HAT", "BOX", "TOP", "COAT", "TAIL", "WIND"] },
  { id: "draw-book", words: ["DRAW", "BACK", "FIRE", "LIGHT", "YEAR", "BOOK"] },
  { id: "space-room", words: ["SPACE", "BAR", "FLY", "PAPER", "WEIGHT", "ROOM"] },
  { id: "door-switch", words: ["DOOR", "STOP", "OVER", "NIGHT", "LIGHT", "SWITCH"] },
  { id: "road-play", words: ["ROAD", "BLOCK", "HEAD", "COUNT", "DOWN", "PLAY"] },
  { id: "wagon-play", words: ["WAGON", "WHEEL", "HOUSE", "WORK", "HORSE", "PLAY"] },
  { id: "cash-sale", words: ["CASH", "BACK", "SPACE", "SHIP", "YARD", "SALE"] },
  { id: "pit-still", words: ["PIT", "STOP", "OVER", "NIGHT", "STAND", "STILL"] },
  { id: "slip-space", words: ["SLIP", "COVER", "UP", "SET", "BACK", "SPACE"] },
  { id: "count-port", words: ["COUNT", "DOWN", "TOWN", "HALL", "PASS", "PORT"] },
  { id: "double-hole", words: ["DOUBLE", "CROSS", "CHECK", "BOOK", "WORM", "HOLE"] },
  { id: "bath-board", words: ["BATH", "HOUSE", "FLY", "PAPER", "CLIP", "BOARD"] },
  { id: "water-dish", words: ["WATER", "PROOF", "READ", "OUT", "SIDE", "DISH"] },
  { id: "wish-wise", words: ["WISH", "BONE", "DRY", "WALL", "CLOCK", "WISE"] },
  { id: "tool-case", words: ["TOOL", "BOX", "TOP", "SIDE", "SHOW", "CASE"] },
  { id: "first-switch", words: ["FIRST", "HAND", "GUN", "FIRE", "LIGHT", "SWITCH"] },
  { id: "wonder-load", words: ["WONDER", "LAND", "SLIDE", "SHOW", "CASE", "LOAD"] },
  { id: "silver-dish", words: ["SILVER", "FISH", "TANK", "TOP", "SIDE", "DISH"] },
  { id: "black-yard", words: ["BLACK", "TOP", "COAT", "TAIL", "BONE", "YARD"] },
  { id: "honey-zone", words: ["HONEY", "MOON", "LIGHT", "YEAR", "END", "ZONE"] },
  { id: "cat-man", words: ["CAT", "FISH", "HOOK", "SHOT", "GUN", "MAN"] },
  { id: "under-beat", words: ["UNDER", "CUT", "OUT", "RUN", "OFF", "BEAT"] },
  { id: "super-burst", words: ["SUPER", "STAR", "DUST", "STORM", "CLOUD", "BURST"] },
  { id: "frame-load", words: ["FRAME", "WORK", "SPACE", "SUIT", "CASE", "LOAD"] },
  { id: "father-bomb", words: ["FATHER", "LAND", "SLIDE", "SHOW", "TIME", "BOMB"] },
  { id: "mud-board", words: ["MUD", "SLIDE", "SHOW", "TIME", "CARD", "BOARD"] },
  { id: "arm-beer", words: ["ARM", "BAND", "STAND", "UP", "ROOT", "BEER"] },
  { id: "sweet-tennis", words: ["SWEET", "CORN", "MEAL", "TIME", "TABLE", "TENNIS"] },
  { id: "winter-card", words: ["WINTER", "COAT", "CHECK", "OUT", "POST", "CARD"] },
  { id: "spear-wife", words: ["SPEAR", "HEAD", "STONE", "WARE", "HOUSE", "WIFE"] },
  { id: "top-track", words: ["TOP", "SIDE", "CAR", "SEAT", "BACK", "TRACK"] },
  { id: "house-way", words: ["HOUSE", "FLY", "OVER", "SLEEP", "WALK", "WAY"] },
  { id: "out-style", words: ["OUT", "BACK", "PACK", "HORSE", "HAIR", "STYLE"] },
  { id: "nut-beat", words: ["NUT", "SHELL", "FISH", "EYE", "BROW", "BEAT"] },
  { id: "toe-record", words: ["TOE", "HOLD", "OUT", "BACK", "TRACK", "RECORD"] },
  { id: "set-son", words: ["SET", "UP", "HILL", "SIDE", "STEP", "SON"] },
  { id: "play-table", words: ["PLAY", "OFF", "SPRING", "TIME", "CARD", "TABLE"] },
  { id: "spot-plan", words: ["SPOT", "CHECK", "BOOK", "END", "GAME", "PLAN"] },
  { id: "trap-way", words: ["TRAP", "DOOR", "STOP", "OVER", "DRIVE", "WAY"] },
  { id: "day-board", words: ["DAY", "TIME", "OUT", "POST", "CARD", "BOARD"] },
  { id: "wing-sheet", words: ["WING", "TIP", "OFF", "ROAD", "WORK", "SHEET"] },
  { id: "crab-down", words: ["CRAB", "GRASS", "LAND", "SLIDE", "SHOW", "DOWN"] },
  { id: "nest-away", words: ["NEST", "EGG", "ROLL", "OUT", "CAST", "AWAY"] },
  { id: "block-trail", words: ["BLOCK", "HEAD", "STONE", "WALL", "PAPER", "TRAIL"] },
  { id: "code-wheel", words: ["CODE", "WORD", "PLAY", "HOUSE", "FLY", "WHEEL"] },
  { id: "tree-lift", words: ["TREE", "HOUSE", "FLY", "WHEEL", "CHAIR", "LIFT"] },
  { id: "car-hand", words: ["CAR", "POOL", "SIDE", "KICK", "OFF", "HAND"] },
  { id: "clock-color", words: ["CLOCK", "WORK", "DAY", "BREAK", "WATER", "COLOR"] },
  { id: "tail-fill", words: ["TAIL", "WIND", "PIPE", "DREAM", "LAND", "FILL"] },
  { id: "dress-knife", words: ["DRESS", "CODE", "WORD", "PLAY", "PEN", "KNIFE"] },
  { id: "gun-tower", words: ["GUN", "FIRE", "TRUCK", "STOP", "WATCH", "TOWER"] },
  { id: "hang-food", words: ["HANG", "OVER", "NIGHT", "WATCH", "DOG", "FOOD"] },
  { id: "face-load", words: ["FACE", "PAINT", "BRUSH", "FIRE", "WORK", "LOAD"] },
  { id: "kick-box", words: ["KICK", "OFF", "SIDE", "ARM", "BAND", "BOX"] },
  { id: "summer-man", words: ["SUMMER", "SCHOOL", "BUS", "STOP", "WATCH", "MAN"] },
  { id: "trade-put", words: ["TRADE", "OFF", "HAND", "GUN", "SHOT", "PUT"] },
  { id: "power-seat", words: ["POWER", "PLAY", "OFF", "SIDE", "CAR", "SEAT"] },
  { id: "table-read", words: ["TABLE", "TOP", "GUN", "FIRE", "PROOF", "READ"] },
  { id: "ground-fall", words: ["GROUND", "WORK", "DAY", "CARE", "FREE", "FALL"] },
  { id: "pay-board", words: ["PAY", "BACK", "STOP", "LIGHT", "SWITCH", "BOARD"] },
  { id: "seat-watch", words: ["SEAT", "BACK", "HAND", "PICK", "POCKET", "WATCH"] },
  { id: "jelly-blank", words: ["JELLY", "FISH", "EYE", "BALL", "POINT", "BLANK"] },
  { id: "heart-coach", words: ["HEART", "BURN", "OUT", "BACK", "STAGE", "COACH"] },
  { id: "pig-flower", words: ["PIG", "TAIL", "BONE", "DRY", "WALL", "FLOWER"] },
  { id: "front-room", words: ["FRONT", "DOOR", "STOP", "LIGHT", "WEIGHT", "ROOM"] },
  { id: "bed-right", words: ["BED", "TIME", "OUT", "RUN", "DOWN", "RIGHT"] },
  { id: "cold-word", words: ["COLD", "FRONT", "DOOR", "STOP", "WATCH", "WORD"] },
  { id: "band-rest", words: ["BAND", "STAND", "UP", "SIDE", "ARM", "REST"] },
  { id: "pull-lift", words: ["PULL", "OVER", "NIGHT", "STAND", "UP", "LIFT"] },
  { id: "pepper-frame", words: ["PEPPER", "CORN", "FIELD", "DAY", "TIME", "FRAME"] },
  { id: "quick-out", words: ["QUICK", "SILVER", "FISH", "EYE", "DROP", "OUT"] },
  { id: "rain-time", words: ["RAIN", "DROP", "OUT", "RUN", "DOWN", "TIME"] },
  { id: "round-out", words: ["ROUND", "UP", "SIDE", "KICK", "STAND", "OUT"] },
  { id: "card-list", words: ["CARD", "TABLE", "TOP", "COAT", "CHECK", "LIST"] },
  { id: "white-hop", words: ["WHITE", "WATER", "FRONT", "DOOR", "BELL", "HOP"] },
  { id: "flash-made", words: ["FLASH", "FLOOD", "GATE", "POST", "MAN", "MADE"] },
  { id: "punch-rack", words: ["PUNCH", "CARD", "TABLE", "TOP", "HAT", "RACK"] },
  { id: "feed-guy", words: ["FEED", "BACK", "DROP", "DOWN", "FALL", "GUY"] },
  { id: "sun-room", words: ["SUN", "DOWN", "SIDE", "ARM", "REST", "ROOM"] },
  { id: "match-field", words: ["MATCH", "STICK", "SHIFT", "WORK", "FORCE", "FIELD"] },
  { id: "bow-neck", words: ["BOW", "TIE", "BREAK", "WATER", "BOTTLE", "NECK"] },
  { id: "safe-player", words: ["SAFE", "GUARD", "DOG", "TAG", "TEAM", "PLAYER"] },
  { id: "flower-board", words: ["FLOWER", "BED", "POST", "CARD", "GAME", "BOARD"] },
  { id: "burn-dish", words: ["BURN", "OUT", "RUN", "DOWN", "SIDE", "DISH"] },
  { id: "long-line", words: ["LONG", "HAND", "PICK", "UP", "STREAM", "LINE"] },
  { id: "bus-land", words: ["BUS", "STOP", "WATCH", "DOG", "WOOD", "LAND"] },
  { id: "goal-man", words: ["GOAL", "POST", "BOX", "TOP", "GUN", "MAN"] },
  { id: "master-bunny", words: ["MASTER", "KEY", "CHAIN", "SAW", "DUST", "BUNNY"] },
  { id: "ghost-play", words: ["GHOST", "TOWN", "HALL", "PASS", "WORD", "PLAY"] },
  { id: "bar-stairs", words: ["BAR", "CODE", "WORD", "COUNT", "DOWN", "STAIRS"] },
  { id: "run-rack", words: ["RUN", "DOWN", "HILL", "TOP", "COAT", "RACK"] },
  { id: "break-hunt", words: ["BREAK", "WATER", "FRONT", "DOOR", "MAN", "HUNT"] },
  { id: "moon-case", words: ["MOON", "ROCK", "SLIDE", "RULE", "BOOK", "CASE"] },
  { id: "watch-holder", words: ["WATCH", "DOG", "WOOD", "WORK", "PLACE", "HOLDER"] },
  { id: "week-tennis", words: ["WEEK", "DAY", "TIME", "CARD", "TABLE", "TENNIS"] },
  { id: "lime-keeper", words: ["LIME", "STONE", "WALL", "FLOWER", "SHOP", "KEEPER"] },
  { id: "drum-gun", words: ["DRUM", "STICK", "UP", "HILL", "TOP", "GUN"] },
  { id: "news-jacket", words: ["NEWS", "PAPER", "WORK", "SPACE", "SUIT", "JACKET"] },
  { id: "stage-drain", words: ["STAGE", "HAND", "GUN", "FIRE", "STORM", "DRAIN"] },
  { id: "cheese-back", words: ["CHEESE", "CAKE", "BATTER", "UP", "SET", "BACK"] },
  { id: "world-away", words: ["WORLD", "WAR", "TIME", "OUT", "CAST", "AWAY"] },
  { id: "smoke-bulb", words: ["SMOKE", "SCREEN", "DOOR", "STOP", "LIGHT", "BULB"] },
  { id: "finger-hand", words: ["FINGER", "TIP", "OFF", "SET", "BACK", "HAND"] },
  { id: "pack-back", words: ["PACK", "HORSE", "RACE", "CAR", "SEAT", "BACK"] },
  { id: "body-light", words: ["BODY", "WORK", "FORCE", "FIELD", "DAY", "LIGHT"] },
  { id: "plant-put", words: ["PLANT", "LIFE", "LONG", "HAND", "OUT", "PUT"] },
  { id: "corn-plan", words: ["CORN", "MEAL", "TIME", "CARD", "GAME", "PLAN"] },
  { id: "paper-dock", words: ["PAPER", "CUT", "BACK", "BONE", "DRY", "DOCK"] },
  { id: "pipe-girl", words: ["PIPE", "DREAM", "LAND", "SLIDE", "SHOW", "GIRL"] },
  { id: "lace-wheel", words: ["LACE", "WORK", "SPACE", "BAR", "FLY", "WHEEL"] },
  { id: "tie-sale", words: ["TIE", "BREAK", "WATER", "FRONT", "YARD", "SALE"] },
  { id: "letter-load", words: ["LETTER", "HEAD", "PHONE", "BOOK", "CASE", "LOAD"] },
  { id: "red-pike", words: ["RED", "HEAD", "SET", "UP", "TURN", "PIKE"] },
  { id: "home-point", words: ["HOME", "WORK", "WEEK", "NIGHT", "STAND", "POINT"] },
  { id: "rose-boat", words: ["ROSE", "WOOD", "WIND", "PIPE", "DREAM", "BOAT"] },
  { id: "whirl-way", words: ["WHIRL", "POOL", "SIDE", "CAR", "PARK", "WAY"] },
  { id: "pine-office", words: ["PINE", "TREE", "TOP", "HAT", "BOX", "OFFICE"] },
  { id: "push-hunt", words: ["PUSH", "CART", "WHEEL", "CHAIR", "MAN", "HUNT"] },
  { id: "cake-way", words: ["CAKE", "BATTER", "UP", "TOWN", "HALL", "WAY"] },
  { id: "gold-wise", words: ["GOLD", "FISH", "HOOK", "SHOT", "CLOCK", "WISE"] },
  { id: "blue-lady", words: ["BLUE", "BIRD", "SONG", "BOOK", "BAG", "LADY"] },
  { id: "horse-bar", words: ["HORSE", "RACE", "CAR", "POOL", "SIDE", "BAR"] },
  { id: "hot-drain", words: ["HOT", "DOG", "WOOD", "WIND", "STORM", "DRAIN"] },
  { id: "iron-track", words: ["IRON", "WORK", "FORCE", "FEED", "BACK", "TRACK"] },
  { id: "high-switch", words: ["HIGH", "SCHOOL", "BUS", "STOP", "LIGHT", "SWITCH"] },
  { id: "mouse-hood", words: ["MOUSE", "TRAP", "DOOR", "BELL", "BOY", "HOOD"] },
  { id: "cross-rule", words: ["CROSS", "ROAD", "BED", "ROCK", "SLIDE", "RULE"] },
  { id: "flag-load", words: ["FLAG", "STONE", "WALL", "CLOCK", "WORK", "LOAD"] },
  { id: "egg-call", words: ["EGG", "ROLL", "OVER", "HEAD", "PHONE", "CALL"] },
  { id: "over-law", words: ["OVER", "NIGHT", "SHIFT", "WORK", "OUT", "LAW"] },
  { id: "lip-room", words: ["LIP", "STICK", "UP", "ROOT", "STOCK", "ROOM"] },
  { id: "hand-worm", words: ["HAND", "PICK", "UP", "DATE", "BOOK", "WORM"] },
  { id: "weather-alike", words: ["WEATHER", "PROOF", "READ", "OUT", "LOOK", "ALIKE"] },
  { id: "mine-lord", words: ["MINE", "FIELD", "DAY", "DREAM", "LAND", "LORD"] },
  { id: "roll-shield", words: ["ROLL", "OVER", "COAT", "TAIL", "WIND", "SHIELD"] },
  { id: "snow-way", words: ["SNOW", "SHOE", "STORE", "FRONT", "DOOR", "WAY"] },
  { id: "short-beat", words: ["SHORT", "CUT", "BACK", "DROP", "DOWN", "BEAT"] },
  { id: "cover-nine", words: ["COVER", "UP", "WIND", "STORM", "CLOUD", "NINE"] },
  { id: "touch-alike", words: ["TOUCH", "DOWN", "TIME", "OUT", "LOOK", "ALIKE"] },
  { id: "test-road", words: ["TEST", "RUN", "OFF", "HAND", "RAIL", "ROAD"] },
  { id: "farm-away", words: ["FARM", "HAND", "STAND", "OUT", "CAST", "AWAY"] },
  { id: "pick-away", words: ["PICK", "UP", "TURN", "OUT", "CAST", "AWAY"] },
  { id: "flood-plan", words: ["FLOOD", "GATE", "POST", "CARD", "GAME", "PLAN"] },
  { id: "tear-keeper", words: ["TEAR", "DROP", "DOWN", "TOWN", "HOUSE", "KEEPER"] },
  { id: "camp-swatter", words: ["CAMP", "FIRE", "SIDE", "BAR", "FLY", "SWATTER"] },
  { id: "waist-keeper", words: ["WAIST", "BAND", "WAGON", "WHEEL", "HOUSE", "KEEPER"] },
  { id: "air-rat", words: ["AIR", "FORCE", "FEED", "BACK", "PACK", "RAT"] },
  { id: "brush-release", words: ["BRUSH", "FIRE", "WORK", "BENCH", "PRESS", "RELEASE"] },
  { id: "full-scout", words: ["FULL", "BACK", "DOOR", "BELL", "BOY", "SCOUT"] },
  { id: "hair-warmer", words: ["HAIR", "PIN", "BALL", "PARK", "BENCH", "WARMER"] },
  { id: "feather-wheel", words: ["FEATHER", "BED", "SIDE", "BAR", "FLY", "WHEEL"] },
  { id: "ever-hall", words: ["EVER", "GREEN", "BACK", "UP", "TOWN", "HALL"] },
  { id: "fire-code", words: ["FIRE", "WOOD", "WORK", "SPACE", "BAR", "CODE"] },
  { id: "cut-mill", words: ["CUT", "OFF", "SET", "UP", "WIND", "MILL"] },
  { id: "field-keeper", words: ["FIELD", "WORK", "WEEK", "DAY", "TIME", "KEEPER"] },
  { id: "tooth-wife", words: ["TOOTH", "PICK", "UP", "TOWN", "HOUSE", "WIFE"] },
  { id: "ear-alike", words: ["EAR", "DRUM", "ROLL", "OUT", "LOOK", "ALIKE"] },
  { id: "down-stool", words: ["DOWN", "PLAY", "OFF", "SIDE", "STEP", "STOOL"] },
  { id: "lock-box", words: ["LOCK", "DOWN", "HILL", "TOP", "HAT", "BOX"] },
  { id: "sword-rope", words: ["SWORD", "FISH", "HOOK", "UP", "TIGHT", "ROPE"] },
  { id: "mind-board", words: ["MIND", "SET", "UP", "TURN", "OVER", "BOARD"] },
  { id: "up-sale", words: ["UP", "SET", "BACK", "BONE", "YARD", "SALE"] },
  { id: "sling-mat", words: ["SLING", "SHOT", "GUN", "FIRE", "PLACE", "MAT"] },
  { id: "tip-away", words: ["TIP", "OFF", "HAND", "OUT", "CAST", "AWAY"] },
  { id: "back-notch", words: ["BACK", "DROP", "DOWN", "HILL", "TOP", "NOTCH"] },
  { id: "shift-keeper", words: ["SHIFT", "KEY", "NOTE", "BOOK", "SHOP", "KEEPER"] },
  { id: "neck-wreck", words: ["NECK", "LACE", "WORK", "SPACE", "SHIP", "WRECK"] },
  { id: "bone-station", words: ["BONE", "DRY", "WALL", "PAPER", "WORK", "STATION"] },
  { id: "copy-room", words: ["COPY", "CAT", "FISH", "EYE", "BALL", "ROOM"] },
  { id: "spring-spoon", words: ["SPRING", "BREAK", "DOWN", "TIME", "TABLE", "SPOON"] },
  { id: "coffee-drop", words: ["COFFEE", "TABLE", "SPOON", "FEED", "BACK", "DROP"] },
  { id: "screen-bench", words: ["SCREEN", "PLAY", "BACK", "GROUND", "WORK", "BENCH"] },
  { id: "race-room", words: ["RACE", "CAR", "PARK", "BENCH", "PRESS", "ROOM"] },
  { id: "spoon-link", words: ["SPOON", "FEED", "BACK", "HAND", "CUFF", "LINK"] },
  { id: "ice-drain", words: ["ICE", "PICK", "UP", "WIND", "STORM", "DRAIN"] },
  { id: "sleep-still", words: ["SLEEP", "OVER", "HEAD", "BAND", "STAND", "STILL"] },
  { id: "take-game", words: ["TAKE", "OVER", "PASS", "BOOK", "END", "GAME"] },
  { id: "turn-pile", words: ["TURN", "OVER", "LAP", "DOG", "WOOD", "PILE"] },
  { id: "base-press", words: ["BASE", "CAMP", "GROUND", "WORK", "BENCH", "PRESS"] },
  { id: "shadow-song", words: ["SHADOW", "PLAY", "OFF", "SHORE", "BIRD", "SONG"] },
  { id: "wild-guy", words: ["WILD", "FIRE", "ARM", "PIT", "FALL", "GUY"] },
  { id: "sheep-wife", words: ["SHEEP", "DOG", "FOOD", "COURT", "HOUSE", "WIFE"] },
  { id: "pocket-mate", words: ["POCKET", "WATCH", "DOG", "TAG", "TEAM", "MATE"] },
  { id: "guard-chart", words: ["GUARD", "RAIL", "ROAD", "WORK", "FLOW", "CHART"] },
  { id: "shell-scout", words: ["SHELL", "FISH", "EYE", "BALL", "BOY", "SCOUT"] },
  { id: "life-way", words: ["LIFE", "GUARD", "RAIL", "CAR", "PARK", "WAY"] },
];

/**
 * The comparison form of a word: letters only, uppercased. Players type with
 * whatever case, spacing and stray punctuation they like; this is what both
 * sides of the check are reduced to before comparing.
 */
export function normalizeWord(input: string): string {
  return input.replace(/[^a-zA-Z]/g, "").toUpperCase();
}

/**
 * How many letters of an answer are shown for free.
 *
 * One, normally — a bare row of dots is a guessing game, and the initial is
 * what turns it into a solvable one. But short connectors like UP or OX are all
 * initial: showing their first letter *is* showing the answer, so they start
 * fully covered and their first letter becomes something to spend a hint on.
 */
export function freeLetters(word: string): number {
  return word.length > 2 ? 1 : 0;
}
