// Curated pool of puzzles for the Word Chain game.
//
// A chain is a run of words where every neighbouring pair makes a compound word
// or a set phrase — SUN·FLOWER, FLOWER·BED, BED·ROOM, and so on. Players see the
// two ends and race to fill everything between them, top down.
//
// Rules the bank follows, so guesses can be checked by exact match:
//
//   * Each link is a real closed compound (BACKPACK) or a standard two-word
//     phrase (PACK RAT). No inflection tricks — "LUCK → CHARM" via *lucky*
//     charm doesn't belong here, because a player who types the right word
//     would still be told they're wrong.
//   * Answers are single words with no spaces or punctuation.
//   * Six words per chain, so every puzzle is exactly four blanks and scores
//     the same as every other one.
//   * Every blank has exactly one answer — from either direction. A blank shown
//     as "follows BED, four letters, starts with R" must not also accept ROCK
//     when the chain wants ROOM. The generator enforces this and drops chains
//     that break it, including ones already in the bank.
//
// The array below is generated. To grow the bank, add links to the LINKS table
// in `scripts/generateWordChains.mjs` and re-run it:
//
//     node scripts/generateWordChains.mjs 750
//
// It keeps every chain already here, ids untouched, and appends until it hits
// the target. Editing a chain by hand is fine too — the generator reads them
// back and works around them — but never renumber one: `player_word_chains_seen`
// is keyed by `id`, so a renamed chain reads as brand new and gets dealt again
// to the people who already solved it.
//
// Why a big bank matters: players never get the same puzzle twice, so the size
// of this list is how many games a regular group gets before selection has to
// fall back to least-seen.

import type { WordChainDifficulty } from "../src/shared/types";

export interface WordChainPuzzle {
  id: string;
  /** The whole chain, first word to last. Ends are given; the rest are blanks. */
  words: string[];
  /**
   * How much narrowing the free first letter has to do: on an easy chain the
   * blank's length alone pins the answer, on a hard one several words fit the
   * shape and only the letter separates them. Derived, so it can move between
   * runs; `id` is the only stable thing about a puzzle.
   */
  difficulty: WordChainDifficulty;
}

export const WORD_CHAINS: WordChainPuzzle[] = [
  { id: "fire-pack-rat", words: ["FIRE", "FLY", "PAPER", "BACK", "PACK", "RAT"], difficulty: "easy" },
  { id: "horse-shop-lift", words: ["HORSE", "SHOE", "LACE", "WORK", "SHOP", "LIFT"], difficulty: "normal" },
  { id: "butter-man-hole", words: ["BUTTER", "FLY", "WHEEL", "CHAIR", "MAN", "HOLE"], difficulty: "easy" },
  { id: "key-hole-punch", words: ["KEY", "NOTE", "BOOK", "WORM", "HOLE", "PUNCH"], difficulty: "normal" },
  { id: "hand-up-root", words: ["HAND", "BAG", "PIPE", "LINE", "UP", "ROOT"], difficulty: "easy" },
  { id: "silver-food-chain", words: ["SILVER", "WARE", "HOUSE", "PLANT", "FOOD", "CHAIN"], difficulty: "easy" },
  { id: "night-water-melon", words: ["NIGHT", "FALL", "OUT", "BREAK", "WATER", "MELON"], difficulty: "hard" },
  { id: "life-point-blank", words: ["LIFE", "GUARD", "RAIL", "WAY", "POINT", "BLANK"], difficulty: "easy" },
  { id: "home-ground-hog", words: ["HOME", "WORK", "HORSE", "PLAY", "GROUND", "HOG"], difficulty: "hard" },
  { id: "super-work-shop", words: ["SUPER", "STAR", "FISH", "NET", "WORK", "SHOP"], difficulty: "easy" },
  { id: "head-up-town", words: ["HEAD", "PHONE", "BOOK", "MARK", "UP", "TOWN"], difficulty: "hard" },
  { id: "red-wheel-chair", words: ["RED", "HEAD", "BAND", "WAGON", "WHEEL", "CHAIR"], difficulty: "easy" },
  { id: "air-land-scape", words: ["AIR", "BAG", "PIPE", "DREAM", "LAND", "SCAPE"], difficulty: "easy" },
  { id: "fire-off-shore", words: ["FIRE", "ARM", "CHAIR", "LIFT", "OFF", "SHORE"], difficulty: "easy" },
  { id: "hot-up-grade", words: ["HOT", "DOG", "TAG", "LINE", "UP", "GRADE"], difficulty: "easy" },
  { id: "snow-life-guard", words: ["SNOW", "MAN", "POWER", "PLANT", "LIFE", "GUARD"], difficulty: "normal" },
  { id: "sun-hat", words: ["SUN", "SET", "UP", "HILL", "TOP", "HAT"], difficulty: "hard" },
  { id: "flower-night", words: ["FLOWER", "SHOP", "FLOOR", "BOARD", "GAME", "NIGHT"], difficulty: "normal" },
  { id: "burn-side", words: ["BURN", "OUT", "POST", "MARK", "DOWN", "SIDE"], difficulty: "hard" },
  { id: "bus-down", words: ["BUS", "STOP", "WATCH", "WORD", "COUNT", "DOWN"], difficulty: "easy" },
  { id: "bar-mate", words: ["BAR", "CODE", "WORD", "PLAY", "ROOM", "MATE"], difficulty: "hard" },
  { id: "score-word", words: ["SCORE", "BOARD", "GAME", "NIGHT", "WATCH", "WORD"], difficulty: "normal" },
  { id: "path-plan", words: ["PATH", "WAY", "SIDE", "BOARD", "GAME", "PLAN"], difficulty: "easy" },
  { id: "stage-keeper", words: ["STAGE", "HAND", "PICK", "POCKET", "BOOK", "KEEPER"], difficulty: "easy" },
  { id: "cheese-blank", words: ["CHEESE", "CAKE", "WALK", "WAY", "POINT", "BLANK"], difficulty: "easy" },
  { id: "lumber-place", words: ["LUMBER", "YARD", "STICK", "SHIFT", "WORK", "PLACE"], difficulty: "easy" },
  { id: "body-mark", words: ["BODY", "GUARD", "DOG", "WOOD", "LAND", "MARK"], difficulty: "normal" },
  { id: "class-work", words: ["CLASS", "ROOM", "SERVICE", "ROAD", "HOUSE", "WORK"], difficulty: "easy" },
  { id: "stair-lamp", words: ["STAIR", "CASE", "WORK", "SHOP", "FLOOR", "LAMP"], difficulty: "normal" },
  { id: "bean-shop", words: ["BEAN", "BAG", "LADY", "FINGER", "PRINT", "SHOP"], difficulty: "easy" },
  { id: "corn-way", words: ["CORN", "FIELD", "DAY", "CARE", "FREE", "WAY"], difficulty: "easy" },
  { id: "chair-way", words: ["CHAIR", "LIFT", "OFF", "HAND", "RAIL", "WAY"], difficulty: "hard" },
  { id: "pipe-walk", words: ["PIPE", "LINE", "DRIVE", "WAY", "SIDE", "WALK"], difficulty: "easy" },
  { id: "dream-down", words: ["DREAM", "TEAM", "WORK", "BOOK", "MARK", "DOWN"], difficulty: "hard" },
  { id: "wind-place", words: ["WIND", "PIPE", "DREAM", "TEAM", "WORK", "PLACE"], difficulty: "normal" },
  { id: "red-wright", words: ["RED", "LINE", "MAN", "POWER", "PLAY", "WRIGHT"], difficulty: "normal" },
  { id: "home-mate", words: ["HOME", "WORK", "BENCH", "PRESS", "ROOM", "MATE"], difficulty: "easy" },
  { id: "root-night", words: ["ROOT", "STOCK", "YARD", "WORK", "WEEK", "NIGHT"], difficulty: "hard" },
  { id: "blue-side", words: ["BLUE", "GRASS", "LAND", "MARK", "DOWN", "SIDE"], difficulty: "hard" },
  { id: "tea-off", words: ["TEA", "BAG", "LADY", "FINGER", "TIP", "OFF"], difficulty: "easy" },
  { id: "mail-book", words: ["MAIL", "MAN", "POWER", "PLAY", "DATE", "BOOK"], difficulty: "hard" },
  { id: "mine-scale", words: ["MINE", "FIELD", "GOAL", "LINE", "UP", "SCALE"], difficulty: "normal" },
  { id: "tape-set", words: ["TAPE", "DECK", "CHAIR", "LIFT", "OFF", "SET"], difficulty: "easy" },
  { id: "pan-dog", words: ["PAN", "CAKE", "WALK", "OVER", "LAP", "DOG"], difficulty: "easy" },
  { id: "test-park", words: ["TEST", "RUN", "DOWN", "SIDE", "CAR", "PARK"], difficulty: "normal" },
  { id: "snake-guy", words: ["SNAKE", "SKIN", "CARE", "FREE", "FALL", "GUY"], difficulty: "easy" },
  { id: "pick-right", words: ["PICK", "POCKET", "BOOK", "MARK", "DOWN", "RIGHT"], difficulty: "normal" },
  { id: "flood-night", words: ["FLOOD", "LIGHT", "YEAR", "END", "GAME", "NIGHT"], difficulty: "normal" },
  { id: "coat-book", words: ["COAT", "TAIL", "BONE", "HEAD", "PHONE", "BOOK"], difficulty: "hard" },
  { id: "air-hunt", words: ["AIR", "BAG", "PIPE", "LINE", "MAN", "HUNT"], difficulty: "easy" },
  { id: "feather-notch", words: ["FEATHER", "BED", "POST", "BOX", "TOP", "NOTCH"], difficulty: "hard" },
  { id: "ever-lift", words: ["EVER", "GREEN", "THUMB", "PRINT", "SHOP", "LIFT"], difficulty: "easy" },
  { id: "skin-blank", words: ["SKIN", "CARE", "FREE", "WAY", "POINT", "BLANK"], difficulty: "easy" },
  { id: "desk-work", words: ["DESK", "TOP", "GUN", "SHOT", "CLOCK", "WORK"], difficulty: "normal" },
  { id: "paint-area", words: ["PAINT", "BRUSH", "FIRE", "ARM", "REST", "AREA"], difficulty: "easy" },
  { id: "tooth-burst", words: ["TOOTH", "BRUSH", "FIRE", "STORM", "CLOUD", "BURST"], difficulty: "easy" },
  { id: "ear-top", words: ["EAR", "DRUM", "ROLL", "OVER", "LAP", "TOP"], difficulty: "easy" },
  { id: "sword-off", words: ["SWORD", "FISH", "EYE", "DROP", "KICK", "OFF"], difficulty: "normal" },
  { id: "team-shore", words: ["TEAM", "WORK", "SHOP", "LIFT", "OFF", "SHORE"], difficulty: "normal" },
  { id: "tip-stock", words: ["TIP", "OFF", "SET", "UP", "ROOT", "STOCK"], difficulty: "easy" },
  { id: "shift-night", words: ["SHIFT", "WORK", "WEEK", "END", "GAME", "NIGHT"], difficulty: "hard" },
  { id: "neck-step", words: ["NECK", "TIE", "BREAK", "DOWN", "SIDE", "STEP"], difficulty: "hard" },
  { id: "gate-walk", words: ["GATE", "POST", "MARK", "UP", "SIDE", "WALK"], difficulty: "hard" },
  { id: "copy-load", words: ["COPY", "CAT", "FISH", "NET", "WORK", "LOAD"], difficulty: "easy" },
  { id: "fall-end", words: ["FALL", "BACK", "GROUND", "RULE", "BOOK", "END"], difficulty: "easy" },
  { id: "coffee-car", words: ["COFFEE", "TABLE", "TOP", "HAT", "BOX", "CAR"], difficulty: "normal" },
  { id: "free-jacket", words: ["FREE", "FALL", "OUT", "LAW", "SUIT", "JACKET"], difficulty: "easy" },
  { id: "fruit-work", words: ["FRUIT", "FLY", "PAPER", "BACK", "GROUND", "WORK"], difficulty: "normal" },
  { id: "grass-stock", words: ["GRASS", "LAND", "MARK", "UP", "ROOT", "STOCK"], difficulty: "hard" },
  { id: "race-line", words: ["RACE", "HORSE", "SHOE", "STORE", "FRONT", "LINE"], difficulty: "normal" },
  { id: "spoon-drive", words: ["SPOON", "FEED", "BAG", "PIPE", "LINE", "DRIVE"], difficulty: "easy" },
  { id: "shadow-put", words: ["SHADOW", "BOX", "TOP", "GUN", "SHOT", "PUT"], difficulty: "easy" },
  { id: "oil-mate", words: ["OIL", "FIELD", "DAY", "DREAM", "TEAM", "MATE"], difficulty: "normal" },
  { id: "post-boat", words: ["POST", "GAME", "NIGHT", "CLUB", "HOUSE", "BOAT"], difficulty: "hard" },
  { id: "wild-house", words: ["WILD", "LIFE", "GUARD", "RAIL", "ROAD", "HOUSE"], difficulty: "easy" },
  { id: "force-team", words: ["FORCE", "FEED", "BAG", "PIPE", "DREAM", "TEAM"], difficulty: "easy" },
  { id: "straw-color", words: ["STRAW", "HAT", "BOX", "SPRING", "WATER", "COLOR"], difficulty: "easy" },
  { id: "fast-release", words: ["FAST", "BALL", "PARK", "BENCH", "PRESS", "RELEASE"], difficulty: "easy" },
  { id: "walk-cap", words: ["WALK", "OUT", "BREAK", "WATER", "BOTTLE", "CAP"], difficulty: "normal" },
  { id: "batter-sale", words: ["BATTER", "UP", "ROOT", "STOCK", "YARD", "SALE"], difficulty: "easy" },
  { id: "rail-band", words: ["RAIL", "ROAD", "BED", "SIDE", "ARM", "BAND"], difficulty: "normal" },
  { id: "chain-nine", words: ["CHAIN", "SAW", "DUST", "STORM", "CLOUD", "NINE"], difficulty: "easy" },
  { id: "foot-list", words: ["FOOT", "LIGHT", "HOUSE", "COAT", "CHECK", "LIST"], difficulty: "hard" },
  { id: "show-back", words: ["SHOW", "DOWN", "HILL", "SIDE", "KICK", "BACK"], difficulty: "hard" },
  { id: "star-piece", words: ["STAR", "POWER", "PLANT", "LIFE", "TIME", "PIECE"], difficulty: "normal" },
  { id: "grape-stream", words: ["GRAPE", "FRUIT", "CAKE", "BATTER", "UP", "STREAM"], difficulty: "easy" },
  { id: "dog-end", words: ["DOG", "HOUSE", "COAT", "CHECK", "BOOK", "END"], difficulty: "hard" },
  { id: "key-feed", words: ["KEY", "NOTE", "CARD", "TABLE", "SPOON", "FEED"], difficulty: "hard" },
  { id: "salt-clip", words: ["SALT", "WATER", "BOTTLE", "NECK", "TIE", "CLIP"], difficulty: "easy" },
  { id: "service-wagon", words: ["SERVICE", "ROAD", "BLOCK", "HEAD", "BAND", "WAGON"], difficulty: "easy" },
  { id: "rock-record", words: ["ROCK", "BAND", "WAGON", "TRAIN", "TRACK", "RECORD"], difficulty: "easy" },
  { id: "candy-team", words: ["CANDY", "BAR", "CODE", "NAME", "TAG", "TEAM"], difficulty: "easy" },
  { id: "ware-load", words: ["WARE", "HOUSE", "PLANT", "LIFE", "BOAT", "LOAD"], difficulty: "hard" },
  { id: "light-board", words: ["LIGHT", "YEAR", "BOOK", "END", "GAME", "BOARD"], difficulty: "normal" },
  { id: "candle-lift", words: ["CANDLE", "LIGHT", "YEAR", "BOOK", "SHOP", "LIFT"], difficulty: "normal" },
  { id: "hat-wind", words: ["HAT", "BOX", "TOP", "COAT", "TAIL", "WIND"], difficulty: "easy" },
  { id: "space-room", words: ["SPACE", "BAR", "FLY", "PAPER", "WEIGHT", "ROOM"], difficulty: "easy" },
  { id: "road-play", words: ["ROAD", "BLOCK", "HEAD", "COUNT", "DOWN", "PLAY"], difficulty: "normal" },
  { id: "slip-space", words: ["SLIP", "COVER", "UP", "SET", "BACK", "SPACE"], difficulty: "easy" },
  { id: "double-hole", words: ["DOUBLE", "CROSS", "CHECK", "BOOK", "WORM", "HOLE"], difficulty: "easy" },
  { id: "wish-wise", words: ["WISH", "BONE", "DRY", "WALL", "CLOCK", "WISE"], difficulty: "easy" },
  { id: "honey-zone", words: ["HONEY", "MOON", "LIGHT", "YEAR", "END", "ZONE"], difficulty: "normal" },
  { id: "cat-man", words: ["CAT", "FISH", "HOOK", "SHOT", "GUN", "MAN"], difficulty: "easy" },
  { id: "super-burst", words: ["SUPER", "STAR", "DUST", "STORM", "CLOUD", "BURST"], difficulty: "easy" },
  { id: "winter-card", words: ["WINTER", "COAT", "CHECK", "OUT", "POST", "CARD"], difficulty: "normal" },
  { id: "out-style", words: ["OUT", "BACK", "PACK", "HORSE", "HAIR", "STYLE"], difficulty: "hard" },
  { id: "spot-plan", words: ["SPOT", "CHECK", "BOOK", "END", "GAME", "PLAN"], difficulty: "normal" },
  { id: "wing-sheet", words: ["WING", "TIP", "OFF", "ROAD", "WORK", "SHEET"], difficulty: "hard" },
  { id: "tail-fill", words: ["TAIL", "WIND", "PIPE", "DREAM", "LAND", "FILL"], difficulty: "easy" },
  { id: "dress-knife", words: ["DRESS", "CODE", "WORD", "PLAY", "PEN", "KNIFE"], difficulty: "easy" },
  { id: "hang-food", words: ["HANG", "OVER", "NIGHT", "WATCH", "DOG", "FOOD"], difficulty: "hard" },
  { id: "summer-man", words: ["SUMMER", "SCHOOL", "BUS", "STOP", "WATCH", "MAN"], difficulty: "easy" },
  { id: "trade-put", words: ["TRADE", "OFF", "HAND", "GUN", "SHOT", "PUT"], difficulty: "normal" },
  { id: "pepper-frame", words: ["PEPPER", "CORN", "FIELD", "DAY", "TIME", "FRAME"], difficulty: "normal" },
  { id: "quick-out", words: ["QUICK", "SILVER", "FISH", "EYE", "DROP", "OUT"], difficulty: "hard" },
  { id: "rain-time", words: ["RAIN", "DROP", "OUT", "RUN", "DOWN", "TIME"], difficulty: "normal" },
  { id: "round-out", words: ["ROUND", "UP", "SIDE", "KICK", "STAND", "OUT"], difficulty: "hard" },
  { id: "card-list", words: ["CARD", "TABLE", "TOP", "COAT", "CHECK", "LIST"], difficulty: "normal" },
  { id: "white-hop", words: ["WHITE", "WATER", "FRONT", "DOOR", "BELL", "HOP"], difficulty: "easy" },
  { id: "punch-rack", words: ["PUNCH", "CARD", "TABLE", "TOP", "HAT", "RACK"], difficulty: "normal" },
  { id: "match-field", words: ["MATCH", "STICK", "SHIFT", "WORK", "FORCE", "FIELD"], difficulty: "easy" },
  { id: "bow-neck", words: ["BOW", "TIE", "BREAK", "WATER", "BOTTLE", "NECK"], difficulty: "easy" },
  { id: "safe-player", words: ["SAFE", "GUARD", "DOG", "TAG", "TEAM", "PLAYER"], difficulty: "easy" },
  { id: "flower-board", words: ["FLOWER", "BED", "POST", "CARD", "GAME", "BOARD"], difficulty: "hard" },
  { id: "bus-land", words: ["BUS", "STOP", "WATCH", "DOG", "WOOD", "LAND"], difficulty: "normal" },
  { id: "goal-man", words: ["GOAL", "POST", "BOX", "TOP", "GUN", "MAN"], difficulty: "normal" },
  { id: "master-bunny", words: ["MASTER", "KEY", "CHAIN", "SAW", "DUST", "BUNNY"], difficulty: "easy" },
  { id: "ghost-play", words: ["GHOST", "TOWN", "HALL", "PASS", "WORD", "PLAY"], difficulty: "easy" },
  { id: "bar-stairs", words: ["BAR", "CODE", "WORD", "COUNT", "DOWN", "STAIRS"], difficulty: "easy" },
  { id: "run-rack", words: ["RUN", "DOWN", "HILL", "TOP", "COAT", "RACK"], difficulty: "hard" },
  { id: "moon-case", words: ["MOON", "ROCK", "SLIDE", "RULE", "BOOK", "CASE"], difficulty: "normal" },
  { id: "week-tennis", words: ["WEEK", "DAY", "TIME", "CARD", "TABLE", "TENNIS"], difficulty: "hard" },
  { id: "stage-drain", words: ["STAGE", "HAND", "GUN", "FIRE", "STORM", "DRAIN"], difficulty: "normal" },
  { id: "cheese-back", words: ["CHEESE", "CAKE", "BATTER", "UP", "SET", "BACK"], difficulty: "easy" },
  { id: "finger-hand", words: ["FINGER", "TIP", "OFF", "SET", "BACK", "HAND"], difficulty: "easy" },
  { id: "body-light", words: ["BODY", "WORK", "FORCE", "FIELD", "DAY", "LIGHT"], difficulty: "easy" },
  { id: "corn-plan", words: ["CORN", "MEAL", "TIME", "CARD", "GAME", "PLAN"], difficulty: "normal" },
  { id: "tie-sale", words: ["TIE", "BREAK", "WATER", "FRONT", "YARD", "SALE"], difficulty: "normal" },
  { id: "push-hunt", words: ["PUSH", "CART", "WHEEL", "CHAIR", "MAN", "HUNT"], difficulty: "easy" },
  { id: "gold-wise", words: ["GOLD", "FISH", "HOOK", "SHOT", "CLOCK", "WISE"], difficulty: "easy" },
  { id: "mine-lord", words: ["MINE", "FIELD", "DAY", "DREAM", "LAND", "LORD"], difficulty: "normal" },
  { id: "cover-nine", words: ["COVER", "UP", "WIND", "STORM", "CLOUD", "NINE"], difficulty: "hard" },
  { id: "test-road", words: ["TEST", "RUN", "OFF", "HAND", "RAIL", "ROAD"], difficulty: "easy" },
  { id: "hair-warmer", words: ["HAIR", "PIN", "BALL", "PARK", "BENCH", "WARMER"], difficulty: "normal" },
  { id: "lock-box", words: ["LOCK", "DOWN", "HILL", "TOP", "HAT", "BOX"], difficulty: "hard" },
  { id: "shift-keeper", words: ["SHIFT", "KEY", "NOTE", "BOOK", "SHOP", "KEEPER"], difficulty: "hard" },
  { id: "bone-station", words: ["BONE", "DRY", "WALL", "PAPER", "WORK", "STATION"], difficulty: "normal" },
  { id: "turn-pile", words: ["TURN", "OVER", "LAP", "DOG", "WOOD", "PILE"], difficulty: "easy" },
  { id: "base-press", words: ["BASE", "CAMP", "GROUND", "WORK", "BENCH", "PRESS"], difficulty: "normal" },
  { id: "shadow-song", words: ["SHADOW", "PLAY", "OFF", "SHORE", "BIRD", "SONG"], difficulty: "normal" },
  { id: "wild-guy", words: ["WILD", "FIRE", "ARM", "PIT", "FALL", "GUY"], difficulty: "easy" },
  { id: "pocket-mate", words: ["POCKET", "WATCH", "DOG", "TAG", "TEAM", "MATE"], difficulty: "normal" },
  { id: "guard-chart", words: ["GUARD", "RAIL", "ROAD", "WORK", "FLOW", "CHART"], difficulty: "normal" },
  { id: "saw-up", words: ["SAW", "DUST", "PAN", "CAKE", "BATTER", "UP"], difficulty: "easy" },
  { id: "book-load", words: ["BOOK", "BAG", "PIPE", "DREAM", "BOAT", "LOAD"], difficulty: "normal" },
  { id: "man-back", words: ["MAN", "POWER", "PLAY", "OFF", "SET", "BACK"], difficulty: "normal" },
  { id: "sun-around", words: ["SUN", "SPOT", "CHECK", "OUT", "RUN", "AROUND"], difficulty: "normal" },
  { id: "match-out", words: ["MATCH", "BOX", "TOP", "COAT", "CHECK", "OUT"], difficulty: "normal" },
  { id: "bow-meet", words: ["BOW", "TIE", "BREAK", "FAST", "TRACK", "MEET"], difficulty: "normal" },
  { id: "safe-board", words: ["SAFE", "GUARD", "DOG", "HOUSE", "KEY", "BOARD"], difficulty: "normal" },
  { id: "flower-water", words: ["FLOWER", "SHOP", "LIFT", "OFF", "SPRING", "WATER"], difficulty: "easy" },
  { id: "burn-seat", words: ["BURN", "OUT", "POST", "BOX", "CAR", "SEAT"], difficulty: "hard" },
  { id: "bus-way", words: ["BUS", "STOP", "OVER", "BOARD", "WALK", "WAY"], difficulty: "hard" },
  { id: "goal-coat", words: ["GOAL", "LINE", "MAN", "POWER", "HOUSE", "COAT"], difficulty: "easy" },
  { id: "master-side", words: ["MASTER", "KEY", "BOARD", "WALK", "WAY", "SIDE"], difficulty: "hard" },
  { id: "truck-line", words: ["TRUCK", "STOP", "WATCH", "DOG", "TAG", "LINE"], difficulty: "easy" },
  { id: "box-charge", words: ["BOX", "CAR", "WASH", "ROOM", "SERVICE", "CHARGE"], difficulty: "hard" },
  { id: "micro-board", words: ["MICRO", "PHONE", "BOOK", "SHOP", "FLOOR", "BOARD"], difficulty: "normal" },
  { id: "bar-holder", words: ["BAR", "FLY", "PAPER", "WORK", "PLACE", "HOLDER"], difficulty: "normal" },
  { id: "run-hole", words: ["RUN", "OFF", "HAND", "GUN", "MAN", "HOLE"], difficulty: "normal" },
  { id: "break-party", words: ["BREAK", "ROOM", "SERVICE", "ROAD", "BLOCK", "PARTY"], difficulty: "easy" },
  { id: "moon-wash", words: ["MOON", "WALK", "WAY", "SIDE", "CAR", "WASH"], difficulty: "normal" },
  { id: "watch-life", words: ["WATCH", "MAN", "POWER", "HOUSE", "PLANT", "LIFE"], difficulty: "easy" },
  { id: "date-stopper", words: ["DATE", "BOOK", "END", "GAME", "SHOW", "STOPPER"], difficulty: "normal" },
  { id: "rule-road", words: ["RULE", "BOOK", "SHOP", "LIFT", "OFF", "ROAD"], difficulty: "easy" },
  { id: "bread-arm", words: ["BREAD", "BOX", "TOP", "GUN", "FIRE", "ARM"], difficulty: "easy" },
  { id: "score-mate", words: ["SCORE", "BOARD", "GAME", "SHOW", "ROOM", "MATE"], difficulty: "hard" },
  { id: "week-tail", words: ["WEEK", "DAY", "LIGHT", "HOUSE", "COAT", "TAIL"], difficulty: "normal" },
  { id: "path-drive", words: ["PATH", "WAY", "SIDE", "WALK", "OVER", "DRIVE"], difficulty: "hard" },
  { id: "lime-station", words: ["LIME", "LIGHT", "WEIGHT", "ROOM", "SERVICE", "STATION"], difficulty: "easy" },
  { id: "drum-floor", words: ["DRUM", "STICK", "SHIFT", "WORK", "SHOP", "FLOOR"], difficulty: "easy" },
  { id: "news-bag", words: ["NEWS", "PAPER", "WORK", "FORCE", "FEED", "BAG"], difficulty: "normal" },
  { id: "look-sake", words: ["LOOK", "OUT", "BACK", "UP", "KEEP", "SAKE"], difficulty: "hard" },
  { id: "tag-blank", words: ["TAG", "LINE", "DRIVE", "WAY", "POINT", "BLANK"], difficulty: "easy" },
  { id: "club-card", words: ["CLUB", "HOUSE", "KEY", "HOLE", "PUNCH", "CARD"], difficulty: "easy" },
  { id: "stage-walk", words: ["STAGE", "HAND", "RAIL", "WAY", "SIDE", "WALK"], difficulty: "hard" },
  { id: "cheese-time", words: ["CHEESE", "CAKE", "WALK", "OVER", "NIGHT", "TIME"], difficulty: "easy" },
  { id: "world-shift", words: ["WORLD", "WAR", "SHIP", "YARD", "STICK", "SHIFT"], difficulty: "hard" },
  { id: "worm-night", words: ["WORM", "HOLE", "PUNCH", "CARD", "GAME", "NIGHT"], difficulty: "normal" },
  { id: "smoke-blank", words: ["SMOKE", "SCREEN", "DOOR", "WAY", "POINT", "BLANK"], difficulty: "normal" },
  { id: "finger-mark", words: ["FINGER", "TIP", "OFF", "SPRING", "WATER", "MARK"], difficulty: "normal" },
  { id: "pack-note", words: ["PACK", "HORSE", "POWER", "HOUSE", "KEY", "NOTE"], difficulty: "easy" },
  { id: "lumber-zone", words: ["LUMBER", "YARD", "WORK", "WEEK", "END", "ZONE"], difficulty: "hard" },
  { id: "body-buster", words: ["BODY", "GUARD", "RAIL", "ROAD", "BLOCK", "BUSTER"], difficulty: "easy" },
  { id: "plant-spoon", words: ["PLANT", "LIFE", "TIME", "CARD", "TABLE", "SPOON"], difficulty: "hard" },
  { id: "stair-stand", words: ["STAIR", "CASE", "WORK", "WEEK", "NIGHT", "STAND"], difficulty: "normal" },
  { id: "care-step", words: ["CARE", "FREE", "FALL", "OUT", "DOOR", "STEP"], difficulty: "normal" },
  { id: "corn-proof", words: ["CORN", "BREAD", "BOX", "SPRING", "WATER", "PROOF"], difficulty: "normal" },
  { id: "paper-store", words: ["PAPER", "CUT", "BACK", "LOG", "BOOK", "STORE"], difficulty: "easy" },
  { id: "pipe-stream", words: ["PIPE", "DREAM", "LAND", "MARK", "DOWN", "STREAM"], difficulty: "hard" },
  { id: "lace-side", words: ["LACE", "WORK", "BENCH", "MARK", "UP", "SIDE"], difficulty: "normal" },
  { id: "tie-blank", words: ["TIE", "BREAK", "WATER", "WAY", "POINT", "BLANK"], difficulty: "easy" },
  { id: "letter-up", words: ["LETTER", "HEAD", "MASTER", "MIND", "SET", "UP"], difficulty: "easy" },
  { id: "dream-chime", words: ["DREAM", "LAND", "MARK", "UP", "WIND", "CHIME"], difficulty: "hard" },
  { id: "wind-back", words: ["WIND", "PIPE", "LINE", "UP", "SET", "BACK"], difficulty: "hard" },
  { id: "red-put", words: ["RED", "HEAD", "BAND", "STAND", "OUT", "PUT"], difficulty: "hard" },
  { id: "home-book", words: ["HOME", "LAND", "MARK", "UP", "DATE", "BOOK"], difficulty: "hard" },
  { id: "sign-service", words: ["SIGN", "POST", "GAME", "SHOW", "ROOM", "SERVICE"], difficulty: "normal" },
  { id: "root-key", words: ["ROOT", "STOCK", "YARD", "STICK", "SHIFT", "KEY"], difficulty: "easy" },
  { id: "room-mat", words: ["ROOM", "SERVICE", "ROAD", "WORK", "PLACE", "MAT"], difficulty: "easy" },
  { id: "tele-load", words: ["TELE", "PHONE", "BOOK", "MARK", "DOWN", "LOAD"], difficulty: "hard" },
  { id: "whirl-made", words: ["WHIRL", "WIND", "PIPE", "LINE", "MAN", "MADE"], difficulty: "hard" },
  { id: "push-keeper", words: ["PUSH", "BACK", "GROUND", "WORK", "BOOK", "KEEPER"], difficulty: "hard" },
  { id: "cake-organ", words: ["CAKE", "BATTER", "UP", "WIND", "PIPE", "ORGAN"], difficulty: "easy" },
  { id: "fly-trip", words: ["FLY", "PAPER", "WORK", "FORCE", "FIELD", "TRIP"], difficulty: "easy" },
  { id: "hall-time", words: ["HALL", "PASS", "WORD", "COUNT", "DOWN", "TIME"], difficulty: "easy" },
  { id: "pillow-goal", words: ["PILLOW", "CASE", "WORK", "FORCE", "FIELD", "GOAL"], difficulty: "easy" },
  { id: "gold-feed", words: ["GOLD", "FISH", "NET", "WORK", "FORCE", "FEED"], difficulty: "easy" },
  { id: "blue-walk", words: ["BLUE", "PRINT", "SHOP", "FLOOR", "BOARD", "WALK"], difficulty: "easy" },
  { id: "horse-right", words: ["HORSE", "PLAY", "OFF", "SET", "UP", "RIGHT"], difficulty: "hard" },
  { id: "hot-load", words: ["HOT", "DOG", "TAG", "TEAM", "WORK", "LOAD"], difficulty: "normal" },
  { id: "iron-lamp", words: ["IRON", "WORK", "BOOK", "SHOP", "FLOOR", "LAMP"], difficulty: "normal" },
  { id: "soap-out", words: ["SOAP", "BOX", "SPRING", "WATER", "FALL", "OUT"], difficulty: "hard" },
  { id: "high-hole", words: ["HIGH", "LIGHT", "YEAR", "BOOK", "WORM", "HOLE"], difficulty: "easy" },
  { id: "sound-road", words: ["SOUND", "CHECK", "OUT", "RUN", "OFF", "ROAD"], difficulty: "hard" },
  { id: "cross-take", words: ["CROSS", "FIRE", "SIDE", "WALK", "OVER", "TAKE"], difficulty: "hard" },
  { id: "flag-setting", words: ["FLAG", "SHIP", "YARD", "WORK", "PLACE", "SETTING"], difficulty: "normal" },
  { id: "egg-search", words: ["EGG", "ROLL", "OVER", "PASS", "WORD", "SEARCH"], difficulty: "normal" },
  { id: "over-pour", words: ["OVER", "BOARD", "GAME", "SHOW", "DOWN", "POUR"], difficulty: "normal" },
  { id: "lip-walk", words: ["LIP", "STICK", "SHIFT", "KEY", "BOARD", "WALK"], difficulty: "normal" },
  { id: "tea-way", words: ["TEA", "HOUSE", "COAT", "TAIL", "GATE", "WAY"], difficulty: "normal" },
  { id: "mail-door", words: ["MAIL", "BOX", "SPRING", "WATER", "FRONT", "DOOR"], difficulty: "normal" },
  { id: "hand-search", words: ["HAND", "PICK", "POCKET", "WATCH", "WORD", "SEARCH"], difficulty: "easy" },
  { id: "mine-proof", words: ["MINE", "FIELD", "DAY", "BREAK", "WATER", "PROOF"], difficulty: "normal" },
  { id: "roll-break", words: ["ROLL", "OUT", "RUN", "OFF", "SPRING", "BREAK"], difficulty: "normal" },
  { id: "snow-hill", words: ["SNOW", "FALL", "OUT", "RUN", "DOWN", "HILL"], difficulty: "hard" },
  { id: "short-house", words: ["SHORT", "STOP", "OVER", "NIGHT", "LIGHT", "HOUSE"], difficulty: "hard" },
  { id: "cover-zone", words: ["COVER", "UP", "DATE", "BOOK", "END", "ZONE"], difficulty: "hard" },
  { id: "touch-load", words: ["TOUCH", "SCREEN", "SHOT", "GUN", "BOAT", "LOAD"], difficulty: "normal" },
  { id: "print-plan", words: ["PRINT", "OUT", "BACK", "GROUND", "FLOOR", "PLAN"], difficulty: "normal" },
  { id: "test-line", words: ["TEST", "RUN", "DOWN", "HILL", "SIDE", "LINE"], difficulty: "hard" },
  { id: "farm-nail", words: ["FARM", "HAND", "BAG", "LADY", "FINGER", "NAIL"], difficulty: "normal" },
  { id: "pick-put", words: ["PICK", "UP", "WIND", "FALL", "OUT", "PUT"], difficulty: "hard" },
  { id: "flood-game", words: ["FLOOD", "LIGHT", "HOUSE", "KEY", "CARD", "GAME"], difficulty: "normal" },
  { id: "lady-game", words: ["LADY", "FINGER", "PRINT", "OUT", "POST", "GAME"], difficulty: "normal" },
  { id: "coat-food", words: ["COAT", "TAIL", "LIGHT", "HOUSE", "PLANT", "FOOD"], difficulty: "easy" },
  { id: "camp-track", words: ["CAMP", "GROUND", "WORK", "HORSE", "RACE", "TRACK"], difficulty: "hard" },
  { id: "tide-basin", words: ["TIDE", "POOL", "SIDE", "CAR", "WASH", "BASIN"], difficulty: "easy" },
  { id: "waist-game", words: ["WAIST", "BAND", "STAND", "OUT", "POST", "GAME"], difficulty: "hard" },
  { id: "air-side", words: ["AIR", "TIME", "CARD", "TABLE", "TOP", "SIDE"], difficulty: "hard" },
  { id: "clip-piece", words: ["CLIP", "BOARD", "GAME", "SHOW", "TIME", "PIECE"], difficulty: "normal" },
  { id: "brush-hunt", words: ["BRUSH", "FIRE", "ARM", "CHAIR", "MAN", "HUNT"], difficulty: "easy" },
  { id: "glass-spin", words: ["GLASS", "WARE", "HOUSE", "COAT", "TAIL", "SPIN"], difficulty: "easy" },
  { id: "full-chart", words: ["FULL", "MOON", "WALK", "OVER", "FLOW", "CHART"], difficulty: "hard" },
  { id: "hide-side", words: ["HIDE", "OUT", "BREAK", "DOWN", "HILL", "SIDE"], difficulty: "hard" },
  { id: "hair-road", words: ["HAIR", "CUT", "BACK", "HAND", "RAIL", "ROAD"], difficulty: "easy" },
  { id: "feather-time", words: ["FEATHER", "BED", "POST", "GAME", "SHOW", "TIME"], difficulty: "hard" },
  { id: "part-walk", words: ["PART", "TIME", "CARD", "GAME", "BOARD", "WALK"], difficulty: "hard" },
  { id: "ever-case", words: ["EVER", "GREEN", "LIGHT", "YEAR", "BOOK", "CASE"], difficulty: "easy" },
  { id: "butter-count", words: ["BUTTER", "FLY", "OVER", "PASS", "WORD", "COUNT"], difficulty: "normal" },
  { id: "case-book", words: ["CASE", "WORK", "HORSE", "BACK", "HAND", "BOOK"], difficulty: "hard" },
  { id: "fire-chart", words: ["FIRE", "TRUCK", "STOP", "OVER", "FLOW", "CHART"], difficulty: "normal" },
  { id: "cut-bug", words: ["CUT", "BACK", "HAND", "BAG", "LADY", "BUG"], difficulty: "hard" },
  { id: "desk-cloud", words: ["DESK", "TOP", "GUN", "FIRE", "STORM", "CLOUD"], difficulty: "normal" },
  { id: "pool-mask", words: ["POOL", "SIDE", "WALK", "OVER", "SLEEP", "MASK"], difficulty: "hard" },
  { id: "field-keeper", words: ["FIELD", "WORK", "WEEK", "NIGHT", "TIME", "KEEPER"], difficulty: "hard" },
  { id: "food-hole", words: ["FOOD", "TRUCK", "STOP", "WATCH", "MAN", "HOLE"], difficulty: "normal" },
  { id: "paint-chair", words: ["PAINT", "BRUSH", "FIRE", "FLY", "WHEEL", "CHAIR"], difficulty: "easy" },
  { id: "tooth-hole", words: ["TOOTH", "PICK", "POCKET", "BOOK", "WORM", "HOLE"], difficulty: "easy" },
  { id: "ear-kick", words: ["EAR", "SHOT", "GUN", "FIRE", "SIDE", "KICK"], difficulty: "hard" },
  { id: "down-mate", words: ["DOWN", "SIDE", "ARM", "REST", "ROOM", "MATE"], difficulty: "normal" },
  { id: "lock-plan", words: ["LOCK", "OUT", "POST", "CARD", "GAME", "PLAN"], difficulty: "hard" },
  { id: "sword-chart", words: ["SWORD", "FISH", "NET", "WORK", "FLOW", "CHART"], difficulty: "easy" },
  { id: "mind-worm", words: ["MIND", "SET", "UP", "DATE", "BOOK", "WORM"], difficulty: "hard" },
  { id: "read-space", words: ["READ", "OUT", "BACK", "GROUND", "WORK", "SPACE"], difficulty: "normal" },
  { id: "team-guy", words: ["TEAM", "WORK", "WEEK", "NIGHT", "FALL", "GUY"], difficulty: "normal" },
  { id: "up-book", words: ["UP", "HILL", "TOP", "COAT", "CHECK", "BOOK"], difficulty: "hard" },
  { id: "wheel-rail", words: ["WHEEL", "HOUSE", "PLANT", "LIFE", "GUARD", "RAIL"], difficulty: "normal" },
  { id: "sling-paper", words: ["SLING", "SHOT", "GUN", "FIRE", "FLY", "PAPER"], difficulty: "easy" },
  { id: "tip-wood", words: ["TIP", "OFF", "HAND", "GUN", "FIRE", "WOOD"], difficulty: "normal" },
  { id: "back-keeper", words: ["BACK", "YARD", "WORK", "BOOK", "SHOP", "KEEPER"], difficulty: "hard" },
  { id: "pass-board", words: ["PASS", "WORD", "PLAY", "HOUSE", "KEY", "BOARD"], difficulty: "normal" },
  { id: "shift-spring", words: ["SHIFT", "WORK", "HORSE", "PLAY", "OFF", "SPRING"], difficulty: "hard" },
  { id: "gate-board", words: ["GATE", "POST", "BOX", "CAR", "WASH", "BOARD"], difficulty: "hard" },
  { id: "side-station", words: ["SIDE", "ARM", "BAND", "WAGON", "TRAIN", "STATION"], difficulty: "easy" },
  { id: "bone-release", words: ["BONE", "YARD", "WORK", "BENCH", "PRESS", "RELEASE"], difficulty: "normal" },
  { id: "copy-down", words: ["COPY", "CAT", "FISH", "EYE", "DROP", "DOWN"], difficulty: "normal" },
  { id: "fall-plant", words: ["FALL", "BACK", "PACK", "HORSE", "POWER", "PLANT"], difficulty: "normal" },
  { id: "coffee-lady", words: ["COFFEE", "TABLE", "SPOON", "FEED", "BAG", "LADY"], difficulty: "easy" },
  { id: "cook-wall", words: ["COOK", "WARE", "HOUSE", "KEY", "STONE", "WALL"], difficulty: "easy" },
  { id: "bottle-lane", words: ["BOTTLE", "NECK", "TIE", "BREAK", "FAST", "LANE"], difficulty: "easy" },
  { id: "word-fight", words: ["WORD", "PLAY", "HOUSE", "PLANT", "FOOD", "FIGHT"], difficulty: "easy" },
  { id: "screen-hole", words: ["SCREEN", "PLAY", "DATE", "BOOK", "WORM", "HOLE"], difficulty: "hard" },
  { id: "fruit-bomb", words: ["FRUIT", "FLY", "OVER", "NIGHT", "TIME", "BOMB"], difficulty: "easy" },
  { id: "name-swipe", words: ["NAME", "TAG", "LINE", "UP", "SIDE", "SWIPE"], difficulty: "easy" },
  { id: "race-warming", words: ["RACE", "HORSE", "POWER", "PLAY", "HOUSE", "WARMING"], difficulty: "normal" },
  { id: "suit-house", words: ["SUIT", "CASE", "WORK", "HORSE", "POWER", "HOUSE"], difficulty: "normal" },
  { id: "ice-room", words: ["ICE", "SKATE", "PARK", "BENCH", "PRESS", "ROOM"], difficulty: "easy" },
  { id: "sleep-boat", words: ["SLEEP", "OVER", "LAP", "TOP", "GUN", "BOAT"], difficulty: "easy" },
  { id: "take-room", words: ["TAKE", "OVER", "NIGHT", "LIGHT", "WEIGHT", "ROOM"], difficulty: "hard" },
  { id: "turn-line", words: ["TURN", "OUT", "RUN", "OFF", "SHORE", "LINE"], difficulty: "normal" },
  { id: "base-flow", words: ["BASE", "CAMP", "FIRE", "FLY", "OVER", "FLOW"], difficulty: "normal" },
  { id: "shadow-spread", words: ["SHADOW", "PLAY", "OFF", "ROAD", "BED", "SPREAD"], difficulty: "easy" },
  { id: "school-horn", words: ["SCHOOL", "YARD", "WORK", "HORSE", "SHOE", "HORN"], difficulty: "hard" },
  { id: "hook-walk", words: ["HOOK", "UP", "HILL", "SIDE", "BOARD", "WALK"], difficulty: "hard" },
  { id: "oil-hole", words: ["OIL", "FIELD", "GOAL", "LINE", "MAN", "HOLE"], difficulty: "normal" },
  { id: "stand-mate", words: ["STAND", "OUT", "BACK", "REST", "ROOM", "MATE"], difficulty: "hard" },
  { id: "shelf-chain", words: ["SHELF", "LIFE", "GUARD", "DOG", "FOOD", "CHAIN"], difficulty: "easy" },
  { id: "wild-port", words: ["WILD", "FIRE", "FLY", "OVER", "PASS", "PORT"], difficulty: "easy" },
  { id: "force-way", words: ["FORCE", "FIELD", "GOAL", "LINE", "DRIVE", "WAY"], difficulty: "normal" },
  { id: "shore-holder", words: ["SHORE", "LINE", "UP", "ROOT", "STOCK", "HOLDER"], difficulty: "easy" },
  { id: "work-way", words: ["WORK", "OUT", "BACK", "HAND", "RAIL", "WAY"], difficulty: "hard" },
  { id: "sheep-kind", words: ["SHEEP", "DOG", "TAG", "LINE", "MAN", "KIND"], difficulty: "easy" },
  { id: "pocket-load", words: ["POCKET", "WATCH", "DOG", "HOUSE", "BOAT", "LOAD"], difficulty: "hard" },
  { id: "shell-warmer", words: ["SHELL", "FISH", "NET", "WORK", "BENCH", "WARMER"], difficulty: "easy" },
  { id: "straw-cloth", words: ["STRAW", "HAT", "BOX", "CAR", "WASH", "CLOTH"], difficulty: "easy" },
  { id: "wash-record", words: ["WASH", "OUT", "BREAK", "FAST", "TRACK", "RECORD"], difficulty: "normal" },
  { id: "walk-arm", words: ["WALK", "OUT", "BREAK", "DOWN", "SIDE", "ARM"], difficulty: "hard" },
  { id: "mid-keeper", words: ["MID", "SUMMER", "SCHOOL", "WORK", "SHOP", "KEEPER"], difficulty: "hard" },
  { id: "hold-rack", words: ["HOLD", "OVER", "LAP", "TOP", "COAT", "RACK"], difficulty: "easy" },
  { id: "tank-break", words: ["TANK", "TOP", "HAT", "BOX", "SPRING", "BREAK"], difficulty: "normal" },
  { id: "shoe-tower", words: ["SHOE", "STORE", "FRONT", "DOOR", "BELL", "TOWER"], difficulty: "easy" },
  { id: "sand-board", words: ["SAND", "PAPER", "BACK", "GROUND", "FLOOR", "BOARD"], difficulty: "hard" },
  { id: "spy-load", words: ["SPY", "GLASS", "WARE", "HOUSE", "BOAT", "LOAD"], difficulty: "hard" },
  { id: "batter-drive", words: ["BATTER", "UP", "HILL", "SIDE", "LINE", "DRIVE"], difficulty: "hard" },
  { id: "head-drain", words: ["HEAD", "SET", "UP", "WIND", "STORM", "DRAIN"], difficulty: "hard" },
  { id: "grand-lane", words: ["GRAND", "STAND", "OUT", "BREAK", "FAST", "LANE"], difficulty: "normal" },
  { id: "green-stop", words: ["GREEN", "THUMB", "PRINT", "OUT", "DOOR", "STOP"], difficulty: "easy" },
  { id: "foot-tower", words: ["FOOT", "PRINT", "OUT", "DOOR", "BELL", "TOWER"], difficulty: "normal" },
  { id: "pop-record", words: ["POP", "UP", "HILL", "SIDE", "TRACK", "RECORD"], difficulty: "hard" },
  { id: "star-way", words: ["STAR", "DUST", "PAN", "CAKE", "WALK", "WAY"], difficulty: "easy" },
  { id: "drop-link", words: ["DROP", "KICK", "BACK", "HAND", "CUFF", "LINK"], difficulty: "easy" },
  { id: "grape-lift", words: ["GRAPE", "FRUIT", "FLY", "WHEEL", "CHAIR", "LIFT"], difficulty: "easy" },
  { id: "war-guy", words: ["WAR", "HEAD", "COUNT", "DOWN", "FALL", "GUY"], difficulty: "normal" },
  { id: "bell-stick", words: ["BELL", "BOY", "FRIEND", "SHIP", "YARD", "STICK"], difficulty: "easy" },
  { id: "night-pal", words: ["NIGHT", "WATCH", "WORD", "PLAY", "PEN", "PAL"], difficulty: "easy" },
  { id: "zip-drive", words: ["ZIP", "CODE", "NAME", "TAG", "LINE", "DRIVE"], difficulty: "easy" },
  { id: "wall-top", words: ["WALL", "PAPER", "BACK", "UP", "HILL", "TOP"], difficulty: "hard" },
  { id: "half-mate", words: ["HALF", "MOON", "LIGHT", "WEIGHT", "ROOM", "MATE"], difficulty: "normal" },
  { id: "stop-chain", words: ["STOP", "OVER", "LAP", "DOG", "FOOD", "CHAIN"], difficulty: "easy" },
  { id: "love-basin", words: ["LOVE", "LETTER", "BOX", "CAR", "WASH", "BASIN"], difficulty: "easy" },
  { id: "service-record", words: ["SERVICE", "ROAD", "BED", "SIDE", "TRACK", "RECORD"], difficulty: "hard" },
  { id: "rock-frame", words: ["ROCK", "BAND", "STAND", "OUT", "DOOR", "FRAME"], difficulty: "normal" },
  { id: "dry-stop", words: ["DRY", "WALL", "PAPER", "CUT", "BACK", "STOP"], difficulty: "normal" },
  { id: "sea-chime", words: ["SEA", "HORSE", "BACK", "UP", "WIND", "CHIME"], difficulty: "hard" },
  { id: "candy-way", words: ["CANDY", "BAR", "FLY", "OVER", "DRIVE", "WAY"], difficulty: "hard" },
  { id: "stick-hand", words: ["STICK", "UP", "SIDE", "KICK", "OFF", "HAND"], difficulty: "hard" },
  { id: "river-still", words: ["RIVER", "SIDE", "ARM", "BAND", "STAND", "STILL"], difficulty: "normal" },
  { id: "ring-watch", words: ["RING", "SIDE", "ARM", "PIT", "STOP", "WATCH"], difficulty: "easy" },
  { id: "eye-hop", words: ["EYE", "DROP", "OUT", "DOOR", "BELL", "HOP"], difficulty: "hard" },
  { id: "off-case", words: ["OFF", "SET", "BACK", "LOG", "BOOK", "CASE"], difficulty: "easy" },
  { id: "draw-track", words: ["DRAW", "BACK", "PACK", "HORSE", "RACE", "TRACK"], difficulty: "hard" },
  { id: "space-light", words: ["SPACE", "BAR", "FLY", "OVER", "NIGHT", "LIGHT"], difficulty: "hard" },
  { id: "road-fire", words: ["ROAD", "BED", "SIDE", "KICK", "BACK", "FIRE"], difficulty: "hard" },
  { id: "cash-park", words: ["CASH", "BACK", "UP", "SIDE", "CAR", "PARK"], difficulty: "normal" },
  { id: "double-load", words: ["DOUBLE", "CROSS", "ROAD", "HOUSE", "BOAT", "LOAD"], difficulty: "hard" },
  { id: "wish-game", words: ["WISH", "BONE", "HEAD", "MASTER", "MIND", "GAME"], difficulty: "normal" },
  { id: "first-tower", words: ["FIRST", "HAND", "GUN", "SHOT", "CLOCK", "TOWER"], difficulty: "normal" },
  { id: "silver-mark", words: ["SILVER", "FISH", "NET", "WORK", "BOOK", "MARK"], difficulty: "normal" },
  { id: "honey-stopper", words: ["HONEY", "MOON", "ROCK", "SLIDE", "SHOW", "STOPPER"], difficulty: "easy" },
  { id: "under-suit", words: ["UNDER", "FOOT", "PRINT", "OUT", "LAW", "SUIT"], difficulty: "normal" },
  { id: "super-line", words: ["SUPER", "POWER", "PLAY", "OFF", "SHORE", "LINE"], difficulty: "hard" },
  { id: "mud-guy", words: ["MUD", "SLIDE", "SHOW", "DOWN", "FALL", "GUY"], difficulty: "hard" },
  { id: "arm-word", words: ["ARM", "PIT", "STOP", "OVER", "PASS", "WORD"], difficulty: "normal" },
  { id: "sweet-man", words: ["SWEET", "TOOTH", "PICK", "POCKET", "WATCH", "MAN"], difficulty: "easy" },
  { id: "spear-wreck", words: ["SPEAR", "HEAD", "BAND", "WAGON", "TRAIN", "WRECK"], difficulty: "easy" },
  { id: "out-book", words: ["OUT", "SIDE", "KICK", "BACK", "LOG", "BOOK"], difficulty: "hard" },
  { id: "day-break", words: ["DAY", "BED", "POST", "BOX", "SPRING", "BREAK"], difficulty: "hard" },
  { id: "nest-way", words: ["NEST", "EGG", "ROLL", "OVER", "DRIVE", "WAY"], difficulty: "hard" },
  { id: "block-wall", words: ["BLOCK", "HEAD", "MASTER", "KEY", "STONE", "WALL"], difficulty: "easy" },
  { id: "tail-load", words: ["TAIL", "BONE", "HEAD", "COUNT", "DOWN", "LOAD"], difficulty: "hard" },
  { id: "face-board", words: ["FACE", "PAINT", "BRUSH", "FIRE", "SIDE", "BOARD"], difficulty: "hard" },
  { id: "kick-show", words: ["KICK", "OFF", "ROAD", "BED", "SIDE", "SHOW"], difficulty: "normal" },
  { id: "summer-barrow", words: ["SUMMER", "CAMP", "FIRE", "FLY", "WHEEL", "BARROW"], difficulty: "normal" },
  { id: "trade-office", words: ["TRADE", "OFF", "ROAD", "BED", "POST", "OFFICE"], difficulty: "easy" },
  { id: "power-club", words: ["POWER", "PLAY", "GROUND", "WORK", "BOOK", "CLUB"], difficulty: "hard" },
  { id: "pay-plan", words: ["PAY", "DAY", "BED", "POST", "GAME", "PLAN"], difficulty: "normal" },
  { id: "pig-room", words: ["PIG", "TAIL", "BONE", "HEAD", "REST", "ROOM"], difficulty: "hard" },
  { id: "cold-rope", words: ["COLD", "CUT", "BACK", "UP", "TIGHT", "ROPE"], difficulty: "easy" },
  { id: "pepper-scape", words: ["PEPPER", "CORN", "DOG", "WOOD", "LAND", "SCAPE"], difficulty: "easy" },
  { id: "quick-book", words: ["QUICK", "SAND", "PAPER", "BACK", "LOG", "BOOK"], difficulty: "normal" },
  { id: "rain-rat", words: ["RAIN", "DROP", "KICK", "BACK", "PACK", "RAT"], difficulty: "normal" },
  { id: "flash-store", words: ["FLASH", "BACK", "PACK", "HORSE", "SHOE", "STORE"], difficulty: "normal" },
  { id: "sun-card", words: ["SUN", "FLOWER", "POT", "HOLE", "PUNCH", "CARD"], difficulty: "normal" },
  { id: "run-tub", words: ["RUN", "OFF", "SHORE", "BIRD", "BATH", "TUB"], difficulty: "easy" },
  { id: "moon-warming", words: ["MOON", "ROCK", "STAR", "POWER", "HOUSE", "WARMING"], difficulty: "easy" },
  { id: "week-pecker", words: ["WEEK", "NIGHT", "WATCH", "DOG", "WOOD", "PECKER"], difficulty: "hard" },
  { id: "news-meet", words: ["NEWS", "PAPER", "CUT", "BACK", "TRACK", "MEET"], difficulty: "normal" },
  { id: "world-case", words: ["WORLD", "WAR", "HEAD", "PHONE", "BOOK", "CASE"], difficulty: "normal" },
  { id: "smoke-kind", words: ["SMOKE", "SCREEN", "SHOT", "GUN", "MAN", "KIND"], difficulty: "normal" },
  { id: "pack-plan", words: ["PACK", "HORSE", "PLAY", "GROUND", "FLOOR", "PLAN"], difficulty: "normal" },
  { id: "letter-card", words: ["LETTER", "HEAD", "MASTER", "KEY", "NOTE", "CARD"], difficulty: "normal" },
  { id: "red-punch", words: ["RED", "HEAD", "MASTER", "KEY", "HOLE", "PUNCH"], difficulty: "easy" },
  { id: "home-hold", words: ["HOME", "BODY", "GUARD", "DOG", "HOUSE", "HOLD"], difficulty: "normal" },
  { id: "horse-man", words: ["HORSE", "HAIR", "PIN", "WHEEL", "CHAIR", "MAN"], difficulty: "normal" },
  { id: "hot-maker", words: ["HOT", "SPOT", "CHECK", "OUT", "LAW", "MAKER"], difficulty: "normal" },
  { id: "high-cast", words: ["HIGH", "SCHOOL", "BUS", "STOP", "OVER", "CAST"], difficulty: "easy" },
  { id: "cross-piece", words: ["CROSS", "ROAD", "BLOCK", "HEAD", "MASTER", "PIECE"], difficulty: "easy" },
  { id: "egg-stick", words: ["EGG", "WHITE", "WATER", "FRONT", "YARD", "STICK"], difficulty: "hard" },
  { id: "lip-press", words: ["LIP", "SERVICE", "ROAD", "WORK", "BENCH", "PRESS"], difficulty: "easy" },
  { id: "camp-by", words: ["CAMP", "FIRE", "ARM", "BAND", "STAND", "BY"], difficulty: "normal" },
  { id: "full-pan", words: ["FULL", "MOON", "ROCK", "STAR", "DUST", "PAN"], difficulty: "easy" },
  { id: "hair-seat", words: ["HAIR", "BRUSH", "FIRE", "SIDE", "CAR", "SEAT"], difficulty: "normal" },
  { id: "ever-beer", words: ["EVER", "GREEN", "BACK", "UP", "ROOT", "BEER"], difficulty: "easy" },
  { id: "ear-keeper", words: ["EAR", "RING", "FINGER", "PRINT", "SHOP", "KEEPER"], difficulty: "easy" },
  { id: "screen-keeper", words: ["SCREEN", "PLAY", "GROUND", "RULE", "BOOK", "KEEPER"], difficulty: "normal" },
  { id: "name-mat", words: ["NAME", "TAG", "TEAM", "WORK", "PLACE", "MAT"], difficulty: "normal" },
  { id: "race-court", words: ["RACE", "HORSE", "POWER", "PLANT", "FOOD", "COURT"], difficulty: "easy" },
  { id: "base-nine", words: ["BASE", "CAMP", "FIRE", "STORM", "CLOUD", "NINE"], difficulty: "normal" },
  { id: "wild-pile", words: ["WILD", "LIFE", "GUARD", "DOG", "WOOD", "PILE"], difficulty: "normal" },
  { id: "work-meet", words: ["WORK", "DAY", "BED", "SIDE", "TRACK", "MEET"], difficulty: "normal" },
  { id: "mid-book", words: ["MID", "SUMMER", "CAMP", "GROUND", "RULE", "BOOK"], difficulty: "normal" },
  { id: "wall-sick", words: ["WALL", "FLOWER", "BED", "SIDE", "CAR", "SICK"], difficulty: "hard" },
  { id: "half-still", words: ["HALF", "MOON", "ROCK", "BAND", "STAND", "STILL"], difficulty: "normal" },
  { id: "love-keeper", words: ["LOVE", "LETTER", "HEAD", "PHONE", "BOOK", "KEEPER"], difficulty: "normal" },
  { id: "rock-put", words: ["ROCK", "STAR", "FISH", "HOOK", "SHOT", "PUT"], difficulty: "easy" },
  { id: "dry-cabin", words: ["DRY", "WALL", "PAPER", "BACK", "LOG", "CABIN"], difficulty: "normal" },
  { id: "sea-shelf", words: ["SEA", "HORSE", "BACK", "LOG", "BOOK", "SHELF"], difficulty: "normal" },
  { id: "ring-knob", words: ["RING", "FINGER", "PRINT", "OUT", "DOOR", "KNOB"], difficulty: "easy" },
  { id: "eye-room", words: ["EYE", "DROP", "KICK", "BACK", "REST", "ROOM"], difficulty: "hard" },
  { id: "double-art", words: ["DOUBLE", "CROSS", "BOW", "TIE", "CLIP", "ART"], difficulty: "easy" },
  { id: "honey-wheel", words: ["HONEY", "MOON", "ROCK", "BAND", "WAGON", "WHEEL"], difficulty: "easy" },
  { id: "super-chain", words: ["SUPER", "STAR", "POWER", "PLANT", "FOOD", "CHAIN"], difficulty: "easy" },
  { id: "sweet-guy", words: ["SWEET", "HEART", "BREAK", "DOWN", "FALL", "GUY"], difficulty: "normal" },
  { id: "nest-suit", words: ["NEST", "EGG", "WHITE", "OUT", "LAW", "SUIT"], difficulty: "normal" },
  { id: "summer-record", words: ["SUMMER", "CAMP", "FIRE", "SIDE", "TRACK", "RECORD"], difficulty: "hard" },
  { id: "quick-chart", words: ["QUICK", "SAND", "PAPER", "WORK", "FLOW", "CHART"], difficulty: "hard" },
  { id: "rain-break", words: ["RAIN", "DROP", "KICK", "OFF", "SPRING", "BREAK"], difficulty: "normal" },
  { id: "egg-lace", words: ["EGG", "WHITE", "WATER", "BOTTLE", "NECK", "LACE"], difficulty: "normal" },
  { id: "race-point", words: ["RACE", "HORSE", "HAIR", "PIN", "BALL", "POINT"], difficulty: "easy" },
  { id: "mid-drain", words: ["MID", "SUMMER", "CAMP", "FIRE", "STORM", "DRAIN"], difficulty: "normal" },
  { id: "double-suit", words: ["DOUBLE", "CROSS", "CHECK", "OUT", "LAW", "SUIT"], difficulty: "easy" },
  { id: "nest-read", words: ["NEST", "EGG", "WHITE", "WATER", "PROOF", "READ"], difficulty: "normal" },
  { id: "double-meet", words: ["DOUBLE", "CROSS", "FIRE", "SIDE", "TRACK", "MEET"], difficulty: "hard" },
  { id: "book-pack", words: ["BOOK", "MARK", "UP", "SET", "BACK", "PACK"], difficulty: "hard" },
  { id: "man-table", words: ["MAN", "POWER", "HOUSE", "KEY", "CARD", "TABLE"], difficulty: "normal" },
  { id: "sun-up", words: ["SUN", "SPOT", "CHECK", "BOOK", "MARK", "UP"], difficulty: "hard" },
  { id: "match-link", words: ["MATCH", "STICK", "SHIFT", "KEY", "CHAIN", "LINK"], difficulty: "easy" },
  { id: "bow-billy", words: ["BOW", "TIE", "BREAK", "DOWN", "HILL", "BILLY"], difficulty: "easy" },
  { id: "safe-spread", words: ["SAFE", "GUARD", "RAIL", "ROAD", "BED", "SPREAD"], difficulty: "easy" },
  { id: "flower-plant", words: ["FLOWER", "BED", "POST", "MAN", "POWER", "PLANT"], difficulty: "hard" },
  { id: "burn-walk", words: ["BURN", "OUT", "DOOR", "WAY", "SIDE", "WALK"], difficulty: "hard" },
  { id: "bus-notch", words: ["BUS", "STOP", "OVER", "LAP", "TOP", "NOTCH"], difficulty: "easy" },
  { id: "goal-load", words: ["GOAL", "POST", "MAN", "POWER", "BOAT", "LOAD"], difficulty: "normal" },
  { id: "master-fall", words: ["MASTER", "KEY", "CARD", "GAME", "NIGHT", "FALL"], difficulty: "normal" },
  { id: "truck-ground", words: ["TRUCK", "STOP", "WATCH", "WORD", "PLAY", "GROUND"], difficulty: "easy" },
  { id: "box-step", words: ["BOX", "SPRING", "WATER", "WAY", "SIDE", "STEP"], difficulty: "normal" },
  { id: "micro-night", words: ["MICRO", "PHONE", "BOOK", "END", "GAME", "NIGHT"], difficulty: "normal" },
  { id: "bar-stage", words: ["BAR", "FLY", "PAPER", "CUT", "BACK", "STAGE"], difficulty: "easy" },
  { id: "run-point", words: ["RUN", "DOWN", "SIDE", "WALK", "WAY", "POINT"], difficulty: "hard" },
  { id: "break-pipe", words: ["BREAK", "OUT", "BACK", "HAND", "BAG", "PIPE"], difficulty: "hard" },
  { id: "moon-time", words: ["MOON", "LIGHT", "HOUSE", "PLANT", "LIFE", "TIME"], difficulty: "normal" },
  { id: "watch-service", words: ["WATCH", "MAN", "POWER", "PLAY", "ROOM", "SERVICE"], difficulty: "normal" },
  { id: "date-step", words: ["DATE", "BOOK", "MARK", "UP", "SIDE", "STEP"], difficulty: "hard" },
  { id: "rule-side", words: ["RULE", "BOOK", "MARK", "DOWN", "HILL", "SIDE"], difficulty: "hard" },
  { id: "score-mare", words: ["SCORE", "BOARD", "WALK", "OVER", "NIGHT", "MARE"], difficulty: "normal" },
  { id: "week-track", words: ["WEEK", "DAY", "BREAK", "DOWN", "SIDE", "TRACK"], difficulty: "hard" },
  { id: "path-still", words: ["PATH", "WAY", "SIDE", "KICK", "STAND", "STILL"], difficulty: "normal" },
  { id: "lime-down", words: ["LIME", "LIGHT", "YEAR", "BOOK", "MARK", "DOWN"], difficulty: "hard" },
  { id: "drum-card", words: ["DRUM", "STICK", "SHIFT", "KEY", "NOTE", "CARD"], difficulty: "normal" },
  { id: "news-side", words: ["NEWS", "FLASH", "FLOOD", "GATE", "WAY", "SIDE"], difficulty: "easy" },
  { id: "look-up", words: ["LOOK", "OUT", "BREAK", "WATER", "MARK", "UP"], difficulty: "hard" },
  { id: "tag-food", words: ["TAG", "LINE", "MAN", "POWER", "PLANT", "FOOD"], difficulty: "easy" },
  { id: "club-blank", words: ["CLUB", "HOUSE", "COAT", "CHECK", "POINT", "BLANK"], difficulty: "normal" },
  { id: "stage-plant", words: ["STAGE", "HAND", "GUN", "MAN", "POWER", "PLANT"], difficulty: "easy" },
  { id: "world-show", words: ["WORLD", "WAR", "TIME", "CARD", "GAME", "SHOW"], difficulty: "hard" },
  { id: "smoke-plan", words: ["SMOKE", "HOUSE", "KEY", "BOARD", "GAME", "PLAN"], difficulty: "normal" },
  { id: "finger-up", words: ["FINGER", "TIP", "OFF", "SHORE", "LINE", "UP"], difficulty: "normal" },
  { id: "pack-stock", words: ["PACK", "HORSE", "BACK", "UP", "ROOT", "STOCK"], difficulty: "hard" },
  { id: "lumber-board", words: ["LUMBER", "YARD", "WORK", "SHOP", "FLOOR", "BOARD"], difficulty: "normal" },
  { id: "body-turn", words: ["BODY", "WORK", "BOOK", "MARK", "UP", "TURN"], difficulty: "hard" },
  { id: "plant-line", words: ["PLANT", "LIFE", "GUARD", "DOG", "TAG", "LINE"], difficulty: "normal" },
  { id: "stair-rest", words: ["STAIR", "WAY", "SIDE", "KICK", "BACK", "REST"], difficulty: "hard" },
  { id: "care-off", words: ["CARE", "FREE", "WAY", "SIDE", "KICK", "OFF"], difficulty: "normal" },
  { id: "corn-rack", words: ["CORN", "BREAD", "BOX", "TOP", "COAT", "RACK"], difficulty: "easy" },
  { id: "chair-head", words: ["CHAIR", "LIFT", "OFF", "ROAD", "BLOCK", "HEAD"], difficulty: "easy" },
  { id: "paper-club", words: ["PAPER", "BACK", "UP", "DATE", "BOOK", "CLUB"], difficulty: "hard" },
  { id: "pipe-guy", words: ["PIPE", "LINE", "UP", "WIND", "FALL", "GUY"], difficulty: "hard" },
  { id: "lace-room", words: ["LACE", "WORK", "HORSE", "BACK", "REST", "ROOM"], difficulty: "hard" },
  { id: "tie-play", words: ["TIE", "BREAK", "WATER", "MARK", "DOWN", "PLAY"], difficulty: "normal" },
  { id: "letter-charge", words: ["LETTER", "HEAD", "REST", "ROOM", "SERVICE", "CHARGE"], difficulty: "hard" },
  { id: "dream-pin", words: ["DREAM", "TEAM", "WORK", "HORSE", "HAIR", "PIN"], difficulty: "normal" },
  { id: "wind-point", words: ["WIND", "FALL", "OUT", "DOOR", "WAY", "POINT"], difficulty: "hard" },
  { id: "red-dream", words: ["RED", "LINE", "UP", "WIND", "PIPE", "DREAM"], difficulty: "normal" },
  { id: "home-spread", words: ["HOME", "ROOM", "SERVICE", "ROAD", "BED", "SPREAD"], difficulty: "easy" },
  { id: "sign-bottle", words: ["SIGN", "POST", "BOX", "SPRING", "WATER", "BOTTLE"], difficulty: "easy" },
  { id: "rose-town", words: ["ROSE", "WOOD", "LAND", "MARK", "DOWN", "TOWN"], difficulty: "hard" },
  { id: "whirl-point", words: ["WHIRL", "POOL", "SIDE", "KICK", "STAND", "POINT"], difficulty: "hard" },
  { id: "log-out", words: ["LOG", "BOOK", "MARK", "DOWN", "FALL", "OUT"], difficulty: "hard" },
  { id: "push-hole", words: ["PUSH", "BACK", "LOG", "BOOK", "WORM", "HOLE"], difficulty: "easy" },
  { id: "cake-keeper", words: ["CAKE", "BATTER", "UP", "DATE", "BOOK", "KEEPER"], difficulty: "hard" },
  { id: "fly-lash", words: ["FLY", "PAPER", "WORK", "HORSE", "BACK", "LASH"], difficulty: "hard" },
  { id: "pillow-made", words: ["PILLOW", "CASE", "WORK", "HORSE", "MAN", "MADE"], difficulty: "hard" },
  { id: "gold-share", words: ["GOLD", "MINE", "FIELD", "DAY", "TIME", "SHARE"], difficulty: "easy" },
  { id: "blue-beat", words: ["BLUE", "PRINT", "SHOP", "LIFT", "OFF", "BEAT"], difficulty: "easy" },
  { id: "horse-party", words: ["HORSE", "PLAY", "OFF", "ROAD", "BLOCK", "PARTY"], difficulty: "normal" },
  { id: "hot-over", words: ["HOT", "HOUSE", "KEY", "BOARD", "WALK", "OVER"], difficulty: "hard" },
  { id: "iron-stairs", words: ["IRON", "WORK", "BENCH", "MARK", "DOWN", "STAIRS"], difficulty: "normal" },
  { id: "soap-load", words: ["SOAP", "BOX", "TOP", "GUN", "BOAT", "LOAD"], difficulty: "normal" },
  { id: "high-link", words: ["HIGH", "SCHOOL", "HOUSE", "KEY", "CHAIN", "LINK"], difficulty: "easy" },
];

/**
 * The comparison form of a word: letters only, uppercased. Players type with
 * whatever case, spacing and stray punctuation they like; this is what both
 * sides of the check are reduced to before comparing.
 */
export function normalizeWord(input: string): string {
  return input.replace(/[^a-zA-Z]/g, "").toUpperCase();
}

/**
 * How many letters of an answer are shown for free.
 *
 * One, normally — a bare row of dots is a guessing game, and the initial is
 * what turns it into a solvable one. But short connectors like UP or OX are all
 * initial: showing their first letter *is* showing the answer, so they start
 * fully covered and their first letter becomes something to spend a hint on.
 */
export function freeLetters(word: string): number {
  return word.length > 2 ? 1 : 0;
}
